#!/usr/bin/env python3
# GENERATED by Storyteling/scripts/security-audit-vendor.py - source sha256 e9841c8c032cc2385f0bdf1eb2b38d372174ff0b522186c24fd3d9116e5ddf56. Do not edit here: edit skills/גנרית/מטא-סקילים/secure-build-discipline/scripts/audit.py and re-run.
# security-audit: ignore-file  (הקובץ הזה מכיל את הדפוסים עצמם, ולכן אינו נסרק)
"""מנוע ביקורת אבטחה - בודק פרויקט אחד לפי שבע משפחות הכשל של `secure-build-discipline`.

למה הוא קיים
------------
הידע (מה לבדוק) היה קיים, ושלוש שכבות רצות בזמן בנייה: סורק הסודות לפני כל
commit, והבדיקה בגיטהאב (gitleaks, osv-scanner, semgrep). אבל **אפס מתוך 13
הממצאים הקריטיים והגבוהים של ביקורת 09/2026 נמצאו בסורק אוטומטי** - כולם נמצאו
בקריאת קוד ע"י סוכן ששאל שאלה. לכן המנוע עושה שני דברים, ולא אחד:

1. **בדיקות מכניות** - מה שמחשב יודע להכריע לבד (סוד עם ברירת-מחדל, טבלה בלי
   RLS, Dockerfile שרץ כ-root, action לא נעול), וגם את שלושת הסורקים הקיימים
   כשהם מותקנים.
2. **משימות לבדיקת סוכן** - לכל משפחה שדורשת שיקול דעת: השאלה מהסקיל, ורשימת
   המקומות בקוד שבהם צריך לשאול אותה. הסוכן עונה בקובץ JSON, ו-`merge` מכניס
   את התשובות לאותה תוצאה.

והכלל שמחזיק את הכל: **מה שלא נבדק נאמר בקול.** כלי שלא מותקן, משימה שעוד לא
נענתה, ריפו שאינו גיט - כולם נרשמים תחת "לא נבדק", ולא נבלעים ב"תקין". מנוע
ששותק על מה שלא בדק הוא בדיוק משפחה ז, "השומר שלא נושך".

⚠️ **לעולם לא מדפיס ערך של סוד** - לא במסך, לא ב-JSON ולא בדוח. ערך ברירת-מחדל
של משתנה-סוד הוא לעיתים הסוד החי עצמו (נמדד ב-noam-whatsapp), ולכן הוא מוסתר.

הרצה
-----
    python3 audit.py scan <נתיב-לפרויקט> [--out DIR] [--no-external] [--history]
    python3 audit.py merge <audit.json> <review.json>

התוצרים (ברירת המחדל: ~/Documents/security-audit/<שם-הפרויקט>/):
    audit.json        התוצאה המובנית - ממנה נגזרת המפה
    audit.md          דוח קריא בעברית, בפורמט של checklist-static-scan.md
    review-brief.md   ההוראות לסוכן שעונה על משימות שיקול הדעת

קודי יציאה: 0 = אין ממצא פתוח בחומרה קריטי/גבוה · 1 = יש · 2 = קלט שגוי או תקלה
במנוע. (כלי חיצוני שנכשל אינו 2 - הוא נרשם תחת "לא נבדק".)

ספריית התקן בלבד. ממקום אחד: skills/גנרית/מטא-סקילים/secure-build-discipline/.
"""
from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import datetime

SCHEMA_VERSION = 1
ENGINE_VERSION = "1.1.0"

# --------------------------------------------------------------------------
# משפחות, חומרה
# --------------------------------------------------------------------------

FAMILIES: dict[str, dict] = {
    "א": {"name": "מי מורשה",
          "question": "מי מורשה להפעיל את זה, ומה קורה כשמישהו שאינו מורשה מנסה? "
                      "ו'מזוהה' אינו 'מורשה': איפה נבדק שהמזהה שייך לקורא?"},
    "ב": {"name": "סודות מנוהלים רע",
          "question": "ומה אם ערך ברירת-המחדל הוא מה שרץ בייצור? ואם השירות ייפרץ - "
                      "מה אפשר לעשות בעולם עם המפתחות שהוא מחזיק?"},
    "ג": {"name": "מידע אישי שנרשם או נחשף",
          "question": "אם הריפו או הלוג הזה ייחשפו מחר - מי האדם שייפגע?"},
    "ד": {"name": "אין תקרה",
          "question": "מי יכול להפעיל את מה שעולה כסף או ששולח משהו, ובכמה? "
                      "יש תקרה על קצב וגם על גודל?"},
    "ה": {"name": "תוכן של זרים במקום של הוראות",
          "question": "כל מחרוזת שנכנסת לפרומפט, ל-HTML או ל-SQL - מי כתב אותה, "
                      "ובאיזה תפקיד היא נוחתת?"},
    "ו": {"name": "תלויות ותשתית",
          "question": "lockfile בגיט, actions נעולים, הרשאות מינימליות, קונטיינר "
                      "שאינו root, ותלויות בלי פרצות ידועות?"},
    "ז": {"name": "השומר שלא נושך",
          "question": "לכל הגנה: יש בדיקה שנכשלת כשמסירים אותה? והשער באמת אוכף, "
                      "או נשאר במצב דיווח?"},
}

SEVERITIES = ("critical", "high", "medium", "low")
SEV_HE = {"critical": "קריטי", "high": "גבוה", "medium": "בינוני", "low": "נמוך"}
SEV_FROM_ANY = {**{s: s for s in SEVERITIES}, **{v: k for k, v in SEV_HE.items()}}
SEV_RANK = {s: i for i, s in enumerate(SEVERITIES)}

CONF_CERTAIN = "ודאי"      # המכונה הכריעה - אין צורך בשיקול דעת
CONF_SUSPECT = "חשוד"      # דפוס שנראה כמו הכשל - סוכן צריך לאשר
CONF_REVIEWED = "נבדק ע\"י סוכן"

# --------------------------------------------------------------------------
# היקף הסריקה
# --------------------------------------------------------------------------

SKIP_DIRS = {
    ".git", "node_modules", "dist", "build", ".next", ".nuxt", ".svelte-kit",
    ".venv", "venv", "env", "__pycache__", "vendor", ".turbo", "coverage",
    "site-packages", ".pytest_cache", ".mypy_cache", ".cache", ".output",
    ".vercel", ".wrangler", "security-audit",
}
MAX_FILE_BYTES = 512 * 1024
MAX_LINE_CHARS = 2000   # שורה ארוכה מזה היא קוד מכווץ, ולא שם כותבים את הכשלים האלה

CODE_EXT = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".vue", ".svelte",
    ".go", ".rb", ".php", ".java", ".rs", ".sh", ".bash",
}
CONFIG_EXT = {".yml", ".yaml", ".toml", ".json", ".ini", ".cfg"}
DATA_EXT = {".csv", ".tsv", ".json", ".jsonl", ".txt"}

TEST_PATH = re.compile(
    r"(?:^|/)(?:tests?|__tests__|spec|specs|e2e|fixtures?|__mocks__)/"
    r"|(?:^|/)test_[^/]+\.py$|_test\.(?:py|go)$|\.(?:test|spec)\.[cm]?[jt]sx?$"
    # הגדרות של כלי-בדיקה: ערך-דמה של סוד כאן הוא בשביל הבדיקות (נמדד ב-studio-gallery)
    r"|(?:^|/)(?:playwright|vitest|jest|cypress)\.config\.[cm]?[jt]s$|(?:^|/)conftest\.py$"
)

LINE_IGNORE = "security-audit: ignore"
FILE_IGNORE = "security-audit: ignore-file"

# --------------------------------------------------------------------------
# דפוסים
#
# ⚠️ חלקם נגזרו מ-scripts/hooks/skill-router-guard.py (secure_build_hit). שם
# המחיר של התראת-שווא הוא שורה של תזכורת; כאן הוא ממצא בדוח. לכן כאן הדפוסים
# צרים יותר: למשל שם של סוד **בלי** ADMIN/AUTH/WEBHOOK, שהם שמות של הגדרות
# תפעוליות לא פחות משמות של סודות.
# --------------------------------------------------------------------------

_SECRET_NAME = r"[A-Z0-9_]*(?:SECRET|TOKEN|PASSWORD|PASSWD|API_?KEY|PRIVATE_?KEY|SIGNING_?KEY|CREDENTIAL)[A-Z0-9_]*"
_SECRET_VAR = r"\w*(?:secret|token|password|api_?key|signature|signing_?key)\w*"

# הערך שנופלים אליו יכול לבוא גם אחרי שרשרת של משתני-סביבה: ב-noam-whatsapp
# `process.env.LEAD_FORM_SECRET || process.env.COUPON_SECRET || "<ערך>"` - שני
# סודות שונים נפלו לאותה מחרוזת כתובה. הגרסה הראשונה של הגלאי חיפשה ערך מיד
# אחרי ה-|| הראשון, ולכן פספסה בדיוק את המקרה מהביקורת.
_PY_ENV = r"os\.(?:environ\.get|getenv)\s*\(\s*['\"]"
_JS_ENV = r"process\.env(?:\.|\[\s*['\"])"
ENV_DEFAULTS = [
    re.compile(_PY_ENV + r"(?P<name>" + _SECRET_NAME + r")['\"]\s*,\s*(?P<q>['\"])(?P<val>.+?)(?P=q)", re.I),
    re.compile(_PY_ENV + r"(?P<name>" + _SECRET_NAME + r")['\"]\s*\)"
               r"(?:\s*or\s*os\.(?:environ\.get|getenv)\([^)]*\))*\s*or\s*(?P<q>['\"])(?P<val>.+?)(?P=q)", re.I),
    re.compile(_JS_ENV + r"(?P<name>" + _SECRET_NAME + r")(?:['\"]\s*\])?"
               r"(?:\s*(?:\|\||\?\?)\s*process\.env(?:\.\w+|\[[^\]]+\]))*"
               r"\s*(?:\|\||\?\?)\s*(?P<q>['\"`])(?P<val>.+?)(?P=q)", re.I),
]

FAIL_OPEN = [
    # if secret and provided != secret:   -> כשהסוד ריק, הבדיקה מדלגת ועוברת
    re.compile(r"\bif\s+(?:self\.)?(" + _SECRET_VAR + r")\s+and\s+[^:\n]*!=", re.I),
    re.compile(r"\bif\s*\(\s*(?:this\.)?(" + _SECRET_VAR + r")\s*&&\s*[^)\n]*!==?", re.I),
    # if (!secret) return next();          -> אין סוד = מעבירים
    re.compile(r"\bif\s*\(\s*!\s*(?:process\.env\.\w+|(?:this\.)?" + _SECRET_VAR + r")\s*\)\s*"
               r"(?:\{\s*)?(?:return\s+)?next\s*\(\s*\)", re.I),
    re.compile(r"\bif\s+not\s+(?:self\.)?(" + _SECRET_VAR + r")\s*:\s*return\s+True\b", re.I),
]

SECRET_IN_URL = re.compile(
    r"[?&](?:key|token|secret|api_?key|apikey|password|access_token|auth)=(?:\$\{|\{|['\"`]\s*\+)", re.I)
CLIENT_SECRET = re.compile(
    r"\b(?:NEXT_PUBLIC|VITE|REACT_APP|EXPO_PUBLIC|PUBLIC)_[A-Z0-9_]*(?:SECRET|SERVICE_ROLE|PRIVATE|PASSWORD)[A-Z0-9_]*")
NONCONST_COMPARE = re.compile(
    r"(?:===?|!==?)\s*(?:process\.env\.(" + _SECRET_NAME + r")|os\.(?:environ\.get|getenv)\(\s*['\"](" + _SECRET_NAME + r"))"
    r"|process\.env\.(" + _SECRET_NAME + r")\s*(?:===?|!==?)", re.I)

# נתיבים
PY_ROUTE = re.compile(
    r"@\w+\.(route|get|post|put|patch|delete|api_route)\s*\(\s*['\"]([^'\"]*)['\"]([^)]*)")
JS_ROUTE = re.compile(
    r"\b(?:app|router|server|api|fastify)\.(get|post|put|patch|delete|all|use)\s*\(\s*['\"`]([^'\"`]*)['\"`]")
NEXT_ROUTE = re.compile(r"export\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE)\b")
ANY_ROUTE = re.compile(
    r"@(?:app|router|bp|blueprint|\w+)\.(?:route|get|post|put|patch|delete|api_route)\s*\("
    r"|\b(?:app|router|server|fastify)\.(?:get|post|put|patch|delete|all)\s*\("
    r"|export\s+(?:async\s+)?function\s+(?:GET|POST|PUT|PATCH|DELETE)\b"
    r"|@(?:Get|Post|Put|Patch|Delete)\s*\(")
ID_PARAM = re.compile(
    r"(?:/:\w*id\b|\[\w*id\]|<(?:int:|str:|uuid:)?\w*id>|\{\w*id\}|req\.params\.\w*[iI]d\b"
    r"|request\.view_args|\b(?:workspace|user|record|lead|account|order|customer|student)_?[iI]d\b)")
STATE_WORDS = re.compile(r"(?:delete|remove|purge|destroy|drop|reset|revoke|wipe)", re.I)

SIG_TOKENS = re.compile(
    r"(hmac|signature|x-hub-signature|compare_digest|timingSafeEqual|verify_?signature|"
    r"verifySignature|constructEvent|svix|x-telegram-bot-api-secret-token|secret_token|"
    r"x-webhook-secret|webhook_secret|verify_webhook|validateRequest|x-twilio-signature)", re.I)
# סימן לכך שה-handler בודק מי שולח - לא רק חתימה: פונקציית הרשאה (_dialer_authorized),
# החזרת 401/403, או העברת הכותרות לפונקציה שמאמתת (handle_webhook(payload, request.headers)).
# בלי זה סומנו 11 handlers מוגנים ב-sales-automation, בבוט ובסטודיו (נמדד 23-09).
HANDLER_AUTH = re.compile(
    r"(authori[sz]|authenticat|unauthori[sz]ed|forbidden|verify\w*\(|_auth\w*\(|require_\w+\(|"
    r"check_\w*(?:secret|token|sig)\w*\(|[(,]\s*(?:request|req)\.headers\b|"
    r"status(?:_code)?\s*[=(:]\s*40[13]\b|,\s*40[13]\s*\)?\s*$|sendStatus\(\s*40[13])", re.I)
BOT_HANDLER = re.compile(
    r"(MessageHandler\(|CommandHandler\(|@bot\.message_handler|new Telegraf\(|\bTelegramBot\(|"
    r"@dp\.message|bot\.on\(\s*['\"](?:message|text)|client\.on\(\s*['\"]messageCreate)")
# ⚠️ בלי re.I על השמות באותיות גדולות: `allowed_updates=Update.ALL_TYPES` של
# python-telegram-bot נראה כמו רשימת-מורשים, ובגללו הבוט של reels-to-email (R2E-1,
# קריטי) עבר את הגלאי בגרסה הראשונה שלו.
BOT_ALLOWLIST = re.compile(
    r"(\bALLOWED_[A-Z_]+|\bAUTHORIZED_[A-Z_]+|\bOWNER_[A-Z_]*ID|(?i:allow_?list|white_?list|"
    r"allowed_(?:user|chat|sender)s?\b|filters\.(?:User|Chat)\(|chat_id\s*(?:==|!=|in|not in)|"
    r"from_user\.id\s*(?:==|!=|in|not in)|ctx\.from\.id|message\.from\.id))")

CORS_WILDCARD = re.compile(
    r"Access-Control-Allow-Origin['\"]?\s*[,:=]\s*['\"]\*|allow_origins\s*=\s*\[\s*['\"]\*"
    r"|\borigin\s*:\s*['\"]\*['\"]|\bcors\(\s*\)")

# רק קריאות שכותבות ליומן (לא getLogger/basicConfig), ורק כשמשתנה עם שם של מידע
# אישי **מוזרק** לשורה - לא כשהמילה מופיעה בטקסט ("Email sent"). הצמצום נמדד על
# reels-to-email ו-blog-checker-cloud: הגרסה הרחבה סימנה 7 שורות, ורק 3 מהן כתבו מידע.
LOG_CALL = re.compile(
    r"(?:console\.(?:log|info|warn|error|debug)|\bprint|\b(?:logger|logging|log)\."
    r"(?:info|debug|warning|warn|error|exception|critical))\s*\(")
_PII_NAME = r"(?:phone|e?mail(?:_?address)?|full_?name|user_?message|message_?text|reply_?text|payload|req\.body)"
PII_IN_LOG = re.compile(
    r"req\.body|request\.(?:json|form|get_json|data)\b|"
    r"JSON\.stringify\(\s*(?:entry|body|payload|msg|message|req|lead|user)\b|"
    # משתנה עם שם של מידע אישי שמוזרק לשורה: {phone} / ${lead.email} / , email) / + phone
    r"(?P<var>(?:\$?\{[^}]*?\b\w*" + _PII_NAME + r"\w*[^}]*\}|[,+]\s*[\w.]*" + _PII_NAME + r"\w*\s*[,)+]))", re.I)
# הממוסך אינו דליפה: String(phone).slice(0, 6)*** / mask(phone) / ***
PII_MASKED = re.compile(r"mask|redact|\*\*\*|\.slice\(\s*0\s*,\s*\d\s*\)|\[:\s*\d\s*\]|hash", re.I)


def pii_log_hit(line: str) -> bool:
    m0 = LOG_CALL.search(line)
    if not m0:
        return False
    call = line[m0.start():]      # רק מה שבתוך קריאת היומן, לא מה שלפניה באותה שורה
    for m in PII_IN_LOG.finditer(call):
        var = m.group("var")
        if var:
            if PII_MASKED.search(var) or re.search(r"\.length\b|\blen\(", var):
                continue   # ממוסך, או אורך בלבד
            if re.search(r"(?:mail|phone)\w*?_?(?:id|result|count|status)\b|\b(?:total|num|count|n)_\w*(?:mail|phone)",
                         var, re.I):
                continue   # email_id / total_emails - מזהה או ספירה, לא כתובת
        return True
    return False


EMAIL = re.compile(r"\b[A-Za-z0-9._%+-]+@([A-Za-z0-9.-]+\.[A-Za-z]{2,})\b")
EMAIL_SAFE_DOMAINS = re.compile(
    r"(?:^|\.)(example\.(?:com|org|net)|test\.com|localhost|noreply\.github\.com|users\.noreply\.github\.com|"
    r"sentry\.io|email\.com|domain\.com|company\.com)$", re.I)
IL_PHONE = re.compile(r"(?<![\d+])(?:\+?972-?|0)5\d[- ]?\d{3}[- ]?\d{4}(?!\d)")

# שלוש צורות. (א) שליחה מפורשת של השגיאה החוצה - בכל קובץ. (ב) `return ..., str(e)` -
# רק בקובץ שהוא נקודת כניסה (נתיב/בוט), כי בסקריפט פנימי זה סתם ערך-חזרה (נמדד:
# 9 מתוך 9 ההתאמות ב-Storyteling היו כאלה). (ג) R2E-3: השגיאה עוברת כארגומנט
# (error_message=str(e)) לפונקציה ששולחת אותה לשולח - אבל לא השמה למשתנה מקומי.
ERROR_LEAK_SEND = re.compile(
    r"(?:res\.(?:send|json|status)|jsonify|reply_text|send_message|sendMessage|HTTPException|Response\(|_json\()"
    r".*(?:\.stack\b|str\(\s*(?:e|exc|err|error|ex)\s*\)|traceback\.format_exc)")
ERROR_LEAK_RETURN = re.compile(r"\breturn\s.*(?:\.stack\b|str\(\s*(?:e|exc|err|error|ex)\s*\)|traceback\.format_exc)")
ERROR_LEAK_KWARG = re.compile(r"[(,]\s*\w*(?:error|detail|reason)\w*=str\(\s*(?:e|exc|err|error|ex)\s*\)"
                              r"|^\s+\w*(?:error|detail|reason)\w*=str\(\s*(?:e|exc|err|error|ex)\s*\)")

RATE_LIMIT = re.compile(
    r"(rate.?limit|ratelimit|slowapi|\blimiter\b|throttl|express-rate-limit|@upstash/ratelimit|"
    r"flask_limiter|Limiter\(|RateLimiter)", re.I)
PAID_API = re.compile(
    r"(anthropic|openai|\.messages\.create\(|chat\.completions|audio\.transcriptions|whisper|"
    r"twilio|resend|sendgrid|runpod|replicate|elevenlabs|graph\.facebook\.com|perplexity|"
    r"api\.telegram\.org/bot|mailgun|postmark)", re.I)
LLM_CALL = re.compile(
    r"(\.messages\.create\(|chat\.completions\.create\(|\.responses\.create\(|generateText\(|"
    r"streamText\(|\bcompletion\(|anthropic\.\w+\(|ChatOpenAI\(|ChatAnthropic\()")

RAW_HTML = re.compile(r"(dangerouslySetInnerHTML|\.innerHTML\s*=|\bv-html\b|\|\s*safe\b|mark_safe\(|\{@html\b)")
HTML_FROM_REQUEST = re.compile(
    r"(?=.*<[a-zA-Z/]|.*value=)(?=.*(?:req\.(?:query|body|params)|request\.(?:args|form|values)|searchParams\.get))"
    r"(?=.*(?:\+\s*\w|\$\{|\{\w+\}))")
# `import markdown as md_lib` ואז `md_lib.markdown(` - כך בדיוק נכתב R2E-2, ולכן
# מספיק שהמודול מיובא, בלי קשר לשם שניתן לו.
MARKDOWN_RENDER = re.compile(
    r"(^[ \t]*import\b[^\n]*\bmarkdown\b|^[ \t]*from markdown import|markdown2\.|mistune\.|\bmarked\(|marked\.parse|"
    r"markdown-it|MarkdownIt\(|showdown|remark-html|\bmd\.render\()", re.M)
SANITIZER = re.compile(r"(bleach|sanitize|DOMPurify|\bnh3\b|sanitize-html|rehype-sanitize|escape\s*=\s*True|html\s*:\s*false)", re.I)
SQL_BUILD = [
    re.compile(r"\.(?:execute|executemany|raw|query|exec)\s*\(\s*f['\"]"),
    re.compile(r"\.(?:execute|query|raw)\s*\(\s*['\"][^'\"]*%s?[^'\"]*['\"]\s*%\s*[\w(]"),
    re.compile(r"\.(?:query|raw|execute|unsafe)\s*\(\s*`[^`]*\$\{"),
    re.compile(r"\$(?:queryRawUnsafe|executeRawUnsafe)\s*\("),
]
PROMPT_SYSTEM = re.compile(
    r"\bsystem(?:_prompt)?\s*[:=]\s*(?:f['\"]|`[^`]*\$\{|[\w.\[\]'\"]+\s*\+\s*\w)"
    r"|role['\"]?\s*:\s*['\"]system['\"].*content['\"]?\s*:\s*(?:f['\"]|`[^`]*\$\{|[\w.]+\s*\+)")

# משתנה עם שם של תוכן שמישהו אחר כתב, שמוזרק לטקסט - מועמד למשימת ה-prompts
# (בנועם: `${priorContext}` בתוך מחרוזת ה-system, N10).
PROMPT_INJECT_VAR = re.compile(
    r"(?:\$\{|\{)\s*\w*(?:context|history|transcript|user_?input|message|lead|reply|comment|email_?body|content)\w*\s*\}",
    re.I)

REPORT_MODE = re.compile(
    r"\b\w*(?:MODE|ENFORCE\w*)\b['\"]?\s*[:=]\s*['\"]?(?:report|report[_-]only|log[_-]only|shadow|monitor|dry[_-]?run)\b"
    r"|\b\w*ENFORCE\w*\b['\"]?\s*[:=]\s*(?:False|false|0|['\"](?:false|0|off)['\"])"
    r"|\b\w*_MODE\s*(?:===?|==)\s*['\"](?:report|log|shadow)['\"]")
GATE_CODE = re.compile(
    r"(status(?:_code)?\s*[=(:]\s*40[13]\b|return\s[^\n]*,\s*40[13]\b|sendStatus\(\s*40[13]|\.status\(\s*40[13]\s*\)|HTTPException\(\s*(?:status_code\s*=\s*)?40[13]|"
    r"abort\(\s*40[13]|Unauthorized|Forbidden|compare_digest|timingSafeEqual)")
GATE_TEST = re.compile(r"(40[13]\b|unauthori[sz]ed|forbidden)", re.I)

# SQL (Supabase / מיגרציות)
SQL_CREATE_TABLE = re.compile(r"create\s+table\s+(?:if\s+not\s+exists\s+)?([\w.\"]+)", re.I)
SQL_ENABLE_RLS = re.compile(
    r"alter\s+table\s+(?:if\s+exists\s+)?(?:only\s+)?([\w.\"]+)\s+enable\s+row\s+level\s+security", re.I)
SQL_OPEN_POLICY = re.compile(r"using\s*\(\s*true\s*\)|with\s+check\s*\(\s*true\s*\)", re.I)
SQL_CREATE_FUNC = re.compile(r"create\s+(?:or\s+replace\s+)?function\s+([\w.\"]+)\s*\(", re.I)
SQL_DEFINER = re.compile(r"security\s+definer", re.I)
SQL_REVOKE_FUNC = re.compile(r"revoke\s+(?:all|execute)[^;]*on\s+function\s+([\w.\"]+)", re.I)
SQL_DEFAULT_PRIV = re.compile(
    r"alter\s+default\s+privileges[^;]*revoke[^;]*(?:execute|all)[^;]*on\s+functions[^;]*\banon\b", re.I | re.S)
SQL_CREATE_VIEW = re.compile(r"create\s+(?:or\s+replace\s+)?view\s+([\w.\"]+)([^;]*)", re.I | re.S)
SQL_GRANT_ANON = re.compile(r"\bgrant\s+[^;]*\bto\s+(?:anon|public)\b", re.I)

# שרשרת אספקה
USES = re.compile(r"^\s*-?\s*uses:\s*([^\s@#]+)@([^\s#]+)")
SHA40 = re.compile(r"^[0-9a-f]{40}$")
WF_INJECTION = re.compile(
    r"\$\{\{\s*github\.event\.(?:issue|pull_request|comment|review|head_commit|commits|discussion)[^}]*"
    r"(?:title|body|message|name|label|head_ref|ref)\b")
DOCKER_USER = re.compile(r"^\s*USER\s+(\S+)", re.I | re.M)
LOCKFILES_JS = ("package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb", "bun.lock", "npm-shrinkwrap.json")
LOCKFILES_PY = ("uv.lock", "poetry.lock", "Pipfile.lock", "pdm.lock")

# הסתרת ערכים שנראים כמו מפתח, בכל קטע קוד שנכנס לפלט.
_KEYISH_LITERAL = re.compile(r"(['\"`])([A-Za-z0-9_\-+/=.:]{12,})\1")
_URL_SECRET_VALUE = re.compile(r"([?&](?:key|token|secret|api_?key|apikey|password|access_token|auth)=)[^&\s'\"`]+", re.I)


_SECRET_ASSIGN = re.compile(
    r"(\b\w*(?:secret|token|password|passwd|api_?key|private_?key|signing_?key)\w*['\"]?\s*[:=]\s*)(['\"`])([^'\"`]+)\2",
    re.I)


def redact(text: str) -> str:
    """מסתיר כל ערך שעשוי להיות סוד: ברירת-מחדל של משתנה-סוד, השמה לשם של סוד,
    ליטרל שנראה כמו מפתח, וערך של פרמטר-סוד בכתובת.

    ⚠️ הסדר חשוב: ברירת-מחדל קצרה כמו "dev-secret" אינה נראית כמו מפתח (אין בה
    ספרה, והיא קצרה מ-12), ובכל זאת היא הסוד החי כשהמשתנה לא מוגדר. לכן היא
    מוסתרת לפי **המקום** שלה בקוד, לפני הבדיקה לפי הצורה.
    """
    for rx in ENV_DEFAULTS:
        text = rx.sub(lambda m: m.group(0)[: m.start("val") - m.start()] + "…"
                      + m.group(0)[m.end("val") - m.start():], text)
    text = _SECRET_ASSIGN.sub(lambda m: f"{m.group(1)}{m.group(2)}…{m.group(2)}", text)

    def lit(m: re.Match) -> str:
        v = m.group(2)
        looks_key = (re.search(r"\d", v) and re.search(r"[A-Za-z]", v) and "/" not in v) or len(v) >= 24
        return f"{m.group(1)}…{m.group(1)}" if looks_key else m.group(0)
    text = _KEYISH_LITERAL.sub(lit, text)
    text = _URL_SECRET_VALUE.sub(r"\1…", text)
    return text


def snippet(line: str, limit: int = 160) -> str:
    s = redact(" ".join(line.strip().split()))
    return s if len(s) <= limit else s[: limit - 1] + "…"


# --------------------------------------------------------------------------
# מבני נתונים
# --------------------------------------------------------------------------

@dataclass
class Finding:
    detector: str
    family: str
    item: str
    severity: str
    confidence: str
    title: str
    file: str = ""
    line: int = 0
    evidence: str = ""
    fix: str = ""
    probe: str = ""
    key: str = ""
    source: str = "engine"

    def finalize(self, raw_line: str = "") -> "Finding":
        basis = " ".join(raw_line.split()) or self.title
        h = hashlib.sha1(basis.encode("utf-8", "replace")).hexdigest()[:10]
        self.key = f"{self.detector}|{self.file}|{h}"
        return self


@dataclass
class Task:
    id: str
    family: str
    items: list
    question: str
    why: str
    candidates: list = field(default_factory=list)
    status: str = "ממתין"


class Project:
    def __init__(self, root: str):
        self.root = os.path.abspath(root)
        self.name = ""
        self.git_top = ""
        self.git: dict = {"is_repo": False}
        self._text: dict[str, list[str] | None] = {}
        self.files: list[str] = []
        self.tracked: set[str] = set()
        self.ignore_globs: list[str] = []
        self.warnings: list[str] = []

    # ---- git ----
    def _git(self, *args: str, cwd: str | None = None) -> tuple[int, str]:
        try:
            p = subprocess.run(["git", "-C", cwd or self.root, *args], capture_output=True,
                               text=True, timeout=60)
            return p.returncode, p.stdout
        except (OSError, subprocess.TimeoutExpired):
            return 1, ""

    def load(self) -> None:
        rc, top = self._git("rev-parse", "--show-toplevel")
        if rc == 0 and top.strip():
            self.git_top = top.strip()
            _, commit = self._git("rev-parse", "HEAD")
            _, branch = self._git("rev-parse", "--abbrev-ref", "HEAD")
            _, remote = self._git("remote", "get-url", "origin")
            _, dirty = self._git("status", "--porcelain")
            remote = re.sub(r"//[^/@]+@", "//", remote.strip())   # בלי אישורים בכתובת
            self.git = {"is_repo": True, "commit": commit.strip()[:12], "branch": branch.strip(),
                        "remote": remote, "dirty": bool(dirty.strip()),
                        "subdir": os.path.relpath(self.root, self.git_top)}
        self.name = os.path.basename(self.git_top if self.git_top and self.git.get("subdir") == "." else self.root)
        self.ignore_globs = self._ignore_patterns()
        if self.git["is_repo"]:
            _, out = self._git("ls-files", "-z", "--cached", "--others", "--exclude-standard")
            _, tracked = self._git("ls-files", "-z", "--cached")
            self.tracked = {p for p in tracked.split("\0") if p}
            files = [p for p in out.split("\0") if p]
        else:
            files = []
            for dp, dns, fns in os.walk(self.root):
                dns[:] = [d for d in dns if d not in SKIP_DIRS]
                for fn in fns:
                    files.append(os.path.relpath(os.path.join(dp, fn), self.root))
        keep = []
        for rel in files:
            rel = rel.replace(os.sep, "/")
            parts = rel.split("/")
            if any(p in SKIP_DIRS for p in parts[:-1]):
                continue
            if self._ignored(rel):
                continue
            if not os.path.isfile(os.path.join(self.root, rel)):
                continue
            keep.append(rel)
        self.files = sorted(set(keep))

    def _ignore_patterns(self) -> list[str]:
        pats = []
        for fn in (".security-audit-ignore", ".semgrepignore"):
            p = os.path.join(self.root, fn)
            if os.path.isfile(p):
                with open(p, encoding="utf-8", errors="replace") as f:
                    for ln in f:
                        ln = ln.strip()
                        if ln and not ln.startswith("#") and not ln.startswith("!"):
                            pats.append(ln)
        return pats

    def _ignored(self, rel: str) -> bool:
        for pat in self.ignore_globs:
            p = pat.lstrip("/")
            if p.endswith("/"):
                if rel.startswith(p) or f"/{p}" in f"/{rel}":
                    return True
                continue
            if fnmatch.fnmatch(rel, p) or fnmatch.fnmatch(os.path.basename(rel), p):
                return True
            if "/" not in p and ("/" + p + "/") in ("/" + rel):
                return True
            if fnmatch.fnmatch(rel, p.rstrip("/") + "/*") or fnmatch.fnmatch(rel, "*/" + p):
                return True
        return False

    # ---- קריאה ----
    def lines(self, rel: str) -> list[str] | None:
        if rel in self._text:
            return self._text[rel]
        path = os.path.join(self.root, rel)
        out: list[str] | None = None
        try:
            if os.path.getsize(path) <= MAX_FILE_BYTES:
                with open(path, "rb") as f:
                    raw = f.read()
                if b"\0" not in raw[:4096]:
                    text = raw.decode("utf-8", "replace")
                    ls = text.splitlines()
                    if not any(FILE_IGNORE in x for x in ls[:5]):
                        out = ls
        except OSError:
            out = None
        self._text[rel] = out
        return out

    def text(self, rel: str) -> str:
        ls = self.lines(rel)
        return "\n".join(ls) if ls else ""

    def ext(self, rel: str) -> str:
        return os.path.splitext(rel)[1].lower()

    def code_files(self, include_tests: bool = False) -> list[str]:
        out = []
        for rel in self.files:
            if self.ext(rel) not in CODE_EXT or rel.endswith(".min.js"):
                continue
            if not include_tests and TEST_PATH.search(rel):
                continue
            out.append(rel)
        return out

    def iter_lines(self, files: list[str]):
        for rel in files:
            ls = self.lines(rel)
            if not ls:
                continue
            for i, ln in enumerate(ls, 1):
                if len(ln) > MAX_LINE_CHARS or LINE_IGNORE in ln:
                    continue
                # שורת הערה אינה אוכפת ואינה חושפת - היא רק מתארת. (בלי זה, קוד שמתעד
                # את הדפוס המסוכן, כמו skill-router-guard.py, מדווח כאילו הוא מבצע אותו.)
                if ln.lstrip().startswith(("#", "//", "/*", "* ", "<!--")) and not ln.startswith("#!"):
                    continue
                if "re.compile(" in ln or "new RegExp(" in ln:
                    continue   # הגדרת דפוס-גלאי אינה הקוד שהוא מחפש
                yield rel, i, ln


# --------------------------------------------------------------------------
# גלאים מכניים. כל גלאי מחזיר ממצאים, ונרשם ב-DETECTORS עם מה שהוא בודק -
# כדי ש"נבדק ונמצא תקין" יופיע בדוח גם כשאין ממצא.
# --------------------------------------------------------------------------

def _f(det, fam, item, sev, conf, title, rel, line_no, raw, fix, probe="") -> Finding:
    return Finding(det, fam, item, sev, conf, title, rel, line_no, snippet(raw), fix, probe).finalize(raw)


# TOKEN הוא גם "טוקן של מודל": STORIES_VISION_MAX_TOKENS ו-TIKTOK_MAX_WORDS_TOKEN_MATCH
# סומנו בהרצה הראשונה על sales-automation ו-aimprove-manychat-bot. שם של מגבלה או ספירה,
# או ערך שהוא מספר או בוליאני, אינו סוד.
_NOT_SECRET_NAME = re.compile(r"MAX|MIN|LIMIT|COUNT|TOKENS\b|_TOKENS_|BUDGET|WINDOW|TTL|EXPIR|LENGTH|SIZE|MATCH|"
                              r"TIMEOUT|RETRIES|_URL\b|_URI\b|_PATH\b|_HEADER\b|_NAME\b|_FILE\b|_DIR\b", re.I)
_NOT_SECRET_VALUE = re.compile(r"^(?:-?\d+(?:\.\d+)?|true|false|yes|no|on|off)$", re.I)


def d_env_default(p: Project) -> list[Finding]:
    out = []
    for rel, i, ln in p.iter_lines(p.code_files()):
        for rx in ENV_DEFAULTS:
            m = rx.search(ln)
            if not m:
                continue
            name, default = m.group("name"), m.group("val")
            if not default.strip() or default.strip() in ("None", "null", "undefined"):
                continue
            if _NOT_SECRET_NAME.search(name) or _NOT_SECRET_VALUE.match(default.strip()):
                continue
            ev = f"{name} ← ברירת מחדל כתובה בקוד ({len(default)} תווים, הערך מוסתר)"
            f = Finding("env-default-secret", "ב", "B2", "high", CONF_CERTAIN,
                        f"הסוד {name} נופל לערך שכתוב בקוד כשהמשתנה לא מוגדר", rel, i, ev,
                        "לקרוא בלי ערך ברירת-מחדל, ולהפיל את השירות בהפעלה כשהמשתנה חסר. "
                        "לבדוק בספק האירוח שהמשתנה מוגדר בייצור - אם לא, הערך שבקוד הוא הסוד החי, "
                        "ויש להחליף אותו.")
            out.append(f.finalize(name + "|" + rel))
            break
    return out


def d_fail_open(p: Project) -> list[Finding]:
    out = []
    for rel, i, ln in p.iter_lines(p.code_files()):
        if any(rx.search(ln) for rx in FAIL_OPEN):
            out.append(_f("fail-open-gate", "א", "B2", "high", CONF_SUSPECT,
                          "שער שנראה כאילו הוא נפתח כשהסוד חסר", rel, i, ln,
                          "שתי שאלות נפרדות: קודם 'האם הסוד מוגדר' - אם לא, לסרב; רק אחר כך "
                          "'האם הוא תואם'. סוד חסר ← סירוב, לעולם לא מעבר.",
                          "לשלוח בקשה בלי הסוד ← חייב 401/403"))
    return out


def d_secret_in_url(p: Project) -> list[Finding]:
    return [_f("secret-in-url", "ב", "B1", "medium", CONF_SUSPECT,
               "סוד מוזרק לתוך כתובת (query string)", rel, i, ln,
               "להעביר את הסוד בכותרת (header) או בגוף הבקשה. כתובות נכנסות ללוגים, להיסטוריה ול-Referer.")
            for rel, i, ln in p.iter_lines(p.code_files()) if SECRET_IN_URL.search(ln)]


def d_client_secret(p: Project) -> list[Finding]:
    files = [r for r in p.files if p.ext(r) in CODE_EXT or os.path.basename(r).startswith(".env")]
    return [_f("client-exposed-secret", "ב", "B1", "high", CONF_CERTAIN,
               "משתנה עם קידומת ציבורית נושא שם של סוד - הוא נשלח לדפדפן", rel, i, ln,
               "סוד לעולם לא בקידומת NEXT_PUBLIC_/VITE_/REACT_APP_. להעביר את הקריאה לשרת.")
            for rel, i, ln in p.iter_lines(files) if CLIENT_SECRET.search(ln)]


def d_nonconst_compare(p: Project) -> list[Finding]:
    return [_f("nonconstant-compare", "ב", "B2", "low", CONF_SUSPECT,
               "השוואת סוד עם == במקום השוואה קבועת-זמן", rel, i, ln,
               "השוואה קבועת-זמן על בייטים, דרך helper אחד לריפו (hmac.compare_digest / crypto.timingSafeEqual).")
            for rel, i, ln in p.iter_lines(p.code_files()) if NONCONST_COMPARE.search(ln)]


def d_env_tracked(p: Project) -> list[Finding]:
    out = []
    if not p.git["is_repo"]:
        return out
    for rel in sorted(p.tracked):
        base = os.path.basename(rel)
        if (base == ".env" or base.startswith(".env.") or base.endswith(".env")) and not re.search(
                r"\.(example|sample|template|dist)$", base):
            out.append(Finding("env-file-tracked", "ב", "B3", "high", CONF_CERTAIN,
                               "קובץ סודות (.env) נמצא בגיט", rel, 0, base,
                               "להוציא מהגיט (git rm --cached), להוסיף ל-.gitignore, ולהחליף כל סוד "
                               "שהיה בו - הוא נשאר בהיסטוריה.").finalize(rel))
    uses_env = any(re.search(r"os\.environ|getenv|process\.env|dotenv", p.text(r))
                   for r in p.code_files()[:400])
    if uses_env:
        rc, _ = p._git("check-ignore", "-q", "--no-index", ".env", cwd=p.git_top)
        if rc != 0:
            out.append(Finding("env-not-ignored", "ב", "B3", "medium", CONF_CERTAIN,
                               "קובץ .env אינו מכוסה ב-.gitignore", ".gitignore", 0, ".env",
                               "להוסיף שורה .env ל-.gitignore לפני שנוצר קובץ כזה.").finalize(".env"))
    return out


def _route_rows(p: Project) -> list[dict]:
    """כל הנתיבים שאפשר לזהות: קובץ, שורה, שיטה, נתיב."""
    rows = []
    for rel, i, ln in p.iter_lines(p.code_files()):
        m = PY_ROUTE.search(ln)
        if m:
            kind, path, rest = m.group(1), m.group(2), m.group(3)
            if kind in ("route", "api_route"):
                ms = re.findall(r"['\"](GET|POST|PUT|PATCH|DELETE)['\"]", rest, re.I)
                methods = [x.upper() for x in ms] or ["GET"]
            else:
                methods = [kind.upper()]
            rows.append({"file": rel, "line": i, "methods": methods, "path": path, "raw": ln})
            continue
        m = JS_ROUTE.search(ln)
        if m and m.group(1) != "use":
            rows.append({"file": rel, "line": i, "methods": [m.group(1).upper()], "path": m.group(2), "raw": ln})
            continue
        m = NEXT_ROUTE.search(ln)
        if m:
            path = "/" + re.sub(r"(^|/)(src/)?(app|pages)/", "", os.path.dirname(rel)).strip("/")
            rows.append({"file": rel, "line": i, "methods": [m.group(1)], "path": path, "raw": ln})
    return rows


def d_state_change_get(p: Project) -> list[Finding]:
    out = []
    for r in _route_rows(p):
        if "GET" in r["methods"] and STATE_WORDS.search(r["path"]):
            out.append(_f("state-change-get", "א", "A5", "medium", CONF_SUSPECT,
                          f"פעולה שמשנה מצב נחשפת ב-GET ({r['path']})", r["file"], r["line"], r["raw"],
                          "פעולה שמשנה מצב - רק ב-POST/DELETE עם אימות. crawler כבר הריץ purge בעבר.",
                          f"GET {r['path']} בלי אימות ← חייב 401/405"))
    return out


def _handler_region(p: Project, rel: str, line_no: int, rows: list[dict]) -> str:
    """הקוד של handler אחד בלבד - מהנתיב עד סוף הפונקציה שלו.

    בדיקה על הקובץ כולו פספסה את N1 (קריטי) בנועם: server.js של 4,000 שורות מכיל
    HMAC במקום אחר לגמרי (טופס הליד), ולכן 'יש חתימה בקובץ' היה נכון - ולא רלוונטי.
    הסוף: השורה הראשונה שמתחילה בעמודה 0 אחרי גוף מוזח (בפייתון: אחרי ה-def; ב-JS:
    כולל ה-`});` הסוגר), לכל היותר 150 שורות, ולעולם לא מעבר לנתיב הבא.
    """
    ls = p.lines(rel) or []
    nxt = [r["line"] for r in rows if r["file"] == rel and r["line"] > line_no]
    hard_end = min(min(nxt) - 1 if nxt else len(ls), line_no + 150)
    out = [ls[line_no - 1]]
    i = line_no
    while i < hard_end and re.match(r"(?:@|def |async def )", ls[i]):   # שאר הדקורטורים וה-def
        out.append(ls[i])
        i += 1
    while i < hard_end:
        ln = ls[i]
        if ln.strip() and not ln[:1].isspace():
            if ln.lstrip().startswith(("}", ")")):
                out.append(ln)
            break
        out.append(ln)
        i += 1
    return "\n".join(out)


def d_webhook_signature(p: Project) -> list[Finding]:
    out = []
    rows = _route_rows(p)
    for r in rows:
        # לפי הנתיב בלבד. "כל POST בקובץ ששמו webhook_server.py" סימן גם דף הסרה ומסך חייגן
        # ב-sales-automation (23-09) - נתיבים שאינם webhook ויש להם אימות משלהם.
        if not re.search(r"hook", r["path"], re.I) or "POST" not in r["methods"] and "ALL" not in r["methods"]:
            continue
        text = p.text(r["file"])
        # אימות שנעשה ב-middleware שמחובר לנתיב (app.use('/webhook', verify...)) - בודקים את הקובץ כולו
        mounted = re.search(r"\.use\(\s*['\"`][^'\"`]*hook[^)]*", text, re.I)
        region = _handler_region(p, r["file"], r["line"], rows)
        if SIG_TOKENS.search(region) or HANDLER_AUTH.search("\n".join(region.splitlines()[1:]) + "\n" + r["raw"]) or (
                mounted and SIG_TOKENS.search(mounted.group(0) + text)):
            continue
        out.append(_f("webhook-no-signature", "א", "E2", "high", CONF_SUSPECT,
                      f"webhook נכנס בלי שום אימות חתימה בקובץ ({r['path']})", r["file"], r["line"], r["raw"],
                      "לאמת חתימת HMAC של הספק (או סוד בכותרת, לא בכתובת), ולסרב כשהסוד חסר.",
                      f"POST {r['path']} בלי חתימה ← חייב 401"))
    return out


def d_bot_allowlist(p: Project) -> list[Finding]:
    out = []
    for rel in p.code_files():
        t = p.text(rel)
        m = BOT_HANDLER.search(t)
        if m and not BOT_ALLOWLIST.search(t):
            line_no = t[: m.start()].count("\n") + 1
            out.append(_f("bot-no-allowlist", "א", "F4", "high", CONF_SUSPECT,
                          "בוט שמגיב לכל מי שכותב לו - אין רשימת-מורשים בקובץ", rel, line_no,
                          t.splitlines()[line_no - 1] if t else "",
                          "רשימת-מורשים (מזהי משתמש/צ'אט) שנבדקת לפני כל פעולה שעולה כסף או ששולחת משהו."))
    return out


def d_cors(p: Project) -> list[Finding]:
    return [_f("cors-wildcard", "א", "A6", "medium", CONF_SUSPECT,
               "CORS פתוח לכל מקור", rel, i, ln,
               "רשימת מקורות מפורשת. לעולם לא '*' יחד עם credentials.")
            for rel, i, ln in p.iter_lines(p.code_files()) if CORS_WILDCARD.search(ln)]


def _migration_files(p: Project) -> list[str]:
    # רק Supabase: שם הטבלאות והפונקציות חשופות לדפדפן דרך PostgREST, ולכן RLS
    # והרשאות anon הם השער. במיגרציה של Prisma/Django האפליקציה מתחברת כבעלים, והמסד
    # אינו חשוף - שם "טבלה בלי RLS" אינו ממצא (נמדד ב-noam-objection-mapper).
    # הנתיב המלא ולא היחסי - כדי שסריקה של תת-התיקייה supabase/ עצמה תזהה אותה.
    return sorted(r for r in p.files if r.endswith(".sql")
                  and re.search(r"(?:^|/)supabase/migrations?/", (p.root + "/" + r).replace(os.sep, "/")))


def _strip_sql_comments(text: str) -> str:
    """מוחק הערות SQL ומשאיר את מספרי השורות. הערה שמזכירה CREATE TABLE או
    security definer נקראה כקוד (aimprove-studio), ולכן ההערות יוצאות לפני כל בדיקה."""
    text = re.sub(r"/\*.*?\*/", lambda m: re.sub(r"[^\n]", " ", m.group(0)), text, flags=re.S)
    return re.sub(r"--[^\n]*", lambda m: " " * len(m.group(0)), text)


# הרשאות שנקבעות דינמית מתוך הקטלוג (DO-block שעובר על pg_proc ומבטל EXECUTE) - כך תוקנה
# ב-virtual-office הפרצה של 31 הפונקציות. אי אפשר לאמת את זה סטטית, ולכן זה "לא נבדק".
SQL_CATALOG_REVOKE = re.compile(r"(?=[\s\S]*\b(?:pg_proc|prosecdef|information_schema\.routines)\b)(?=[\s\S]*\brevoke\b)", re.I)
SQL_BULK_REVOKE = re.compile(r"revoke\s+(?:all|execute)[^;]*on\s+all\s+functions\s+in\s+schema\s+public[^;]*\banon\b", re.I | re.S)


def _norm(name: str) -> str:
    return name.replace('"', "").split(".")[-1].lower()


def d_migrations(p: Project) -> list[Finding]:
    out = []
    migs = _migration_files(p)
    if not migs:
        return out
    texts = {m: _strip_sql_comments(p.text(m)) for m in migs}
    blob = "\n".join(texts.values())
    enabled = {_norm(n) for n in SQL_ENABLE_RLS.findall(blob)}
    revoked = {_norm(n) for n in SQL_REVOKE_FUNC.findall(blob)}
    dynamic_revoke = any(SQL_CATALOG_REVOKE.match(t) and re.search(r"do\s+\$", t, re.I) for t in texts.values())
    bulk_revoke = bool(SQL_BULK_REVOKE.search(blob))
    if dynamic_revoke:
        p.warnings.append("הרשאות EXECUTE על פונקציות נקבעות דינמית מהקטלוג - לא נבדק סטטית; "
                          "נדרשת בדיקה חיה (has_function_privilege('anon', ...)).")
    for rel in migs:
        ls = p.lines(rel) or []
        text = texts[rel]
        for m in SQL_CREATE_TABLE.finditer(text):
            name = _norm(m.group(1))
            if name not in enabled:
                ln = text[: m.start()].count("\n") + 1
                out.append(_f("table-without-rls", "א", "A2", "high", CONF_CERTAIN,
                              f"הטבלה {name} נוצרת בלי RLS", rel, ln, ls[ln - 1],
                              f"alter table {name} enable row level security; ומדיניות מפורשת לכל פקודה."))
        for m in SQL_OPEN_POLICY.finditer(text):
            ln = text[: m.start()].count("\n") + 1
            out.append(_f("open-policy", "א", "A2", "high", CONF_SUSPECT,
                          "מדיניות RLS שפותחת הכל (using true / with check true)", rel, ln, ls[ln - 1],
                          "לצמצם את המדיניות לבעלים או לתפקיד השירות בלבד."))
        funcs = [(fm.start(), _norm(fm.group(1))) for fm in SQL_CREATE_FUNC.finditer(text)]
        for dm in SQL_DEFINER.finditer(text):
            prev = [f for f in funcs if f[0] < dm.start()]
            if not prev or dynamic_revoke or bulk_revoke:
                continue
            name = prev[-1][1]
            # פונקציית טריגר (returns trigger) אינה ניתנת לקריאה דרך ה-API, ולכן אין מה לבטל
            if re.search(r"returns\s+trigger\b", text[prev[-1][0]: dm.start()], re.I):
                continue
            if name not in revoked:
                ln = text[: prev[-1][0]].count("\n") + 1
                out.append(_f("definer-without-revoke", "א", "A1", "high", CONF_CERTAIN,
                              f"הפונקציה {name} היא SECURITY DEFINER ואין revoke execute עליה", rel, ln,
                              ls[ln - 1],
                              f"revoke execute on function {name}(...) from public, anon, authenticated; "
                              "ו-set search_path."))
        for m in SQL_CREATE_VIEW.finditer(text):
            if "security_invoker" not in m.group(2).lower():
                ln = text[: m.start()].count("\n") + 1
                out.append(_f("view-without-invoker", "א", "A3", "medium", CONF_CERTAIN,
                              f"ה-view {_norm(m.group(1))} רץ כבעלים ועוקף RLS", rel, ln, ls[ln - 1],
                              "with (security_invoker = true)."))
        for m in SQL_GRANT_ANON.finditer(text):
            ln = text[: m.start()].count("\n") + 1
            out.append(_f("grant-to-anon", "א", "A2", "medium", CONF_SUSPECT,
                          "הרשאה ל-anon/public במיגרציה", rel, ln, ls[ln - 1],
                          "לוודא שהגישה האנונימית מכוונת ומוגבלת ב-RLS."))
    if not SQL_DEFAULT_PRIV.search(blob):
        out.append(Finding("no-default-privileges-revoke", "א", "A1", "medium", CONF_CERTAIN,
                           "אין במיגרציות ALTER DEFAULT PRIVILEGES שמונע גישת anon לפונקציות חדשות",
                           migs[0], 1, "",
                           "במיגרציה: alter default privileges in schema public revoke execute on "
                           "functions from anon, authenticated; ואותו דבר ל-tables.").finalize("default-priv"))
    return out


def d_pii_logs(p: Project) -> list[Finding]:
    return [_f("pii-in-logs", "ג", "E1", "medium", CONF_SUSPECT,
               "לוג שנראה כאילו הוא כותב מידע אישי או גוף בקשה", rel, i, ln,
               "helper לרדקציה (טלפון/מייל ממוסכים, בלי גוף בקשה ובלי תוכן שיחה).")
            for rel, i, ln in p.iter_lines(p.code_files()) if pii_log_hit(ln)]


def d_pii_files(p: Project) -> list[Finding]:
    out = []
    for rel in p.files:
        if p.ext(rel) not in DATA_EXT or TEST_PATH.search(rel):
            continue
        base = os.path.basename(rel)
        if base in ("package.json", "package-lock.json", "tsconfig.json", "composer.json") or base.startswith("."):
            continue
        t = p.text(rel)
        if not t:
            continue
        emails = {e.lower() for e, dom in ((m.group(0), m.group(1)) for m in EMAIL.finditer(t))
                  if not EMAIL_SAFE_DOMAINS.search(dom)}
        phones = {re.sub(r"\D", "", m.group(0))[-9:] for m in IL_PHONE.finditer(t)}
        if len(emails) + len(phones) >= 3:
            out.append(Finding("pii-data-file", "ג", "E1", "medium", CONF_SUSPECT,
                               f"קובץ נתונים עם פרטי קשר של אנשים ({len(emails)} מיילים, {len(phones)} טלפונים)",
                               rel, 0, "הערכים עצמם לא מוצגים",
                               "אם הריפו ייחשף - מי ייפגע? להוציא מהגיט (והיסטוריה) או להחליף בנתוני-דמה.")
                       .finalize(rel))
    return out


def d_error_leak(p: Project) -> list[Finding]:
    entry = {r for r in p.code_files() if ANY_ROUTE.search(p.text(r)) or BOT_HANDLER.search(p.text(r))}
    return [_f("error-leak", "ג", "E3", "low", CONF_SUSPECT,
               "הודעת שגיאה פנימית חוזרת למשתמש", rel, i, ln,
               "למשתמש - הודעה כללית; הפרטים ללוג בלבד.")
            for rel, i, ln in p.iter_lines(p.code_files())
            if ERROR_LEAK_SEND.search(ln) or ERROR_LEAK_KWARG.search(ln)
            or (rel in entry and ERROR_LEAK_RETURN.search(ln))]


def d_rate_limit(p: Project) -> list[Finding]:
    routes = _route_rows(p)
    bots = [r for r in p.code_files() if BOT_HANDLER.search(p.text(r))]
    if not routes and not bots:
        return []
    if any(RATE_LIMIT.search(p.text(r)) for r in p.code_files()):
        return []
    anchor = routes[0] if routes else {"file": bots[0], "line": 1, "raw": ""}
    return [_f("no-rate-limit", "ד", "C1", "medium", CONF_SUSPECT,
               f"יש {len(routes)} נתיבים ו-{len(bots)} בוטים, ואין שום הגבלת קצב בפרויקט",
               anchor["file"], anchor["line"], anchor.get("raw", ""),
               "הגבלת קצב (וגודל) על כל נתיב לא-מאומת שעולה כסף או ששולח משהו, ועל כל מסך התחברות.")]


# innerHTML שמקבל מחרוזת קבועה אינו פתח - אין בו תוכן של אף אחד.
_STATIC_ASSIGN = re.compile(r"\.innerHTML\s*=\s*(['\"`])[^'\"`$+]*\1\s*;?\s*$")


def d_raw_html(p: Project) -> list[Finding]:
    # ⚠️ רק קובצי קוד. בקובצי .html סטטיים (דפי נחיתה, מצגות, עורכים) נמדדו ב-Storyteling
    # 90 מופעים, כמעט כולם של תוכן שהדף עצמו בונה. הם נכנסים למשימת הסוכן ה-html
    # ולא לרשימת הממצאים, שאחרת טובעת ברעש.
    return [_f("raw-html", "ה", "C4", "medium", CONF_SUSPECT,
               "HTML גולמי שעוקף את ההגנה של הספרייה", rel, i, ln,
               "escape לכל תוכן שמשתמש שולט בו, או sanitizer (DOMPurify/bleach) לפני ההצגה.")
            for rel, i, ln in p.iter_lines(p.code_files()) if RAW_HTML.search(ln) and not _STATIC_ASSIGN.search(ln)]


def d_html_from_request(p: Project) -> list[Finding]:
    return [_f("html-from-request", "ה", "C4", "high", CONF_SUSPECT,
               "פרמטר מהבקשה נכנס ל-HTML בלי escape", rel, i, ln,
               "escapeHtml על כל ערך מהבקשה לפני שהוא נכנס ל-HTML.",
               "לשלוח בפרמטר '\"><script>' ולוודא שהוא חוזר מקודד")
            for rel, i, ln in p.iter_lines(p.code_files()) if HTML_FROM_REQUEST.search(ln)]


def d_markdown(p: Project) -> list[Finding]:
    out = []
    for rel in p.code_files():
        t = p.text(rel)
        m = MARKDOWN_RENDER.search(t)
        if m and not SANITIZER.search(t):
            ln = t[: m.start()].count("\n") + 1
            out.append(_f("markdown-unsanitized", "ה", "C4", "medium", CONF_SUSPECT,
                          "Markdown מומר ל-HTML בלי sanitizer", rel, ln, t.splitlines()[ln - 1],
                          "לסנן את ה-HTML שנוצר (bleach/nh3/DOMPurify), במיוחד כשהמקור הוא מודל או משתמש."))
    return out


def d_sql(p: Project) -> list[Finding]:
    return [_f("sql-string-build", "ה", "C2", "high", CONF_SUSPECT,
               "SQL שנבנה ממחרוזת במקום פרמטרים", rel, i, ln,
               "שאילתה עם פרמטרים (placeholders) - לעולם לא f-string / ${} בתוך SQL.")
            for rel, i, ln in p.iter_lines(p.code_files()) if any(rx.search(ln) for rx in SQL_BUILD)]


def d_prompt_system(p: Project) -> list[Finding]:
    return [_f("prompt-system-interpolation", "ה", "F1", "medium", CONF_SUSPECT,
               "תוכן משתנה מוזרק לתפקיד ה-system של המודל", rel, i, ln,
               "תוכן שמקורו מבחוץ נכנס כהודעה מסומנת (messages), לא למקום של ההוראות.")
            for rel, i, ln in p.iter_lines(p.code_files()) if PROMPT_SYSTEM.search(ln)]


def _workflows(p: Project) -> list[str]:
    return [r for r in p.files if re.match(r"(?:.*/)?\.github/workflows/[^/]+\.ya?ml$", r)]


def d_supply_chain(p: Project) -> list[Finding]:
    out = []
    files = set(p.files)
    for rel in p.files:
        base, d = os.path.basename(rel), os.path.dirname(rel)
        sib = lambda n: (f"{d}/{n}" if d else n) in files  # noqa: E731
        if base == "package.json":
            try:
                pkg = json.loads(p.text(rel) or "{}")
            except json.JSONDecodeError:
                pkg = {}
            if (pkg.get("dependencies") or pkg.get("devDependencies")) and not any(sib(n) for n in LOCKFILES_JS):
                # lockfile בתיקיית-אב (monorepo) גם הוא נעילה
                parents = [x for x in files if os.path.basename(x) in LOCKFILES_JS and d.startswith(os.path.dirname(x))]
                if not parents:
                    out.append(Finding("lockfile-missing", "ו", "E4a", "low", CONF_CERTAIN,
                                       "package.json בלי lockfile", rel, 0, base,
                                       "להריץ install ולהכניס את ה-lockfile לגיט.").finalize(rel))
        elif re.match(r"requirements[\w.-]*\.txt$", base):
            reqs = [x.strip() for x in (p.lines(rel) or []) if x.strip() and not x.strip().startswith(("#", "-"))]
            loose = [x for x in reqs if "==" not in x and "@" not in x]
            if loose and not any(sib(n) for n in LOCKFILES_PY):
                out.append(Finding("lockfile-missing", "ו", "E4a", "low", CONF_CERTAIN,
                                   f"{len(loose)} תלויות Python בלי גרסה נעולה", rel, 0, base,
                                   "לנעול גרסאות (==) או להשתמש ב-lockfile (uv.lock/poetry.lock).").finalize(rel))
    wfs = _workflows(p)
    for rel in wfs:
        ls = p.lines(rel) or []
        text = "\n".join(ls)
        loose = [m for m in (USES.match(x) for x in ls) if m and not m.group(1).startswith("./")
                 and not SHA40.match(m.group(2))]
        if loose:
            out.append(Finding("actions-unpinned", "ו", "E4b", "low", CONF_CERTAIN,
                               f"{len(loose)} actions לא נעולים ל-SHA", rel, 0, loose[0].group(0).strip(),
                               "לנעול כל uses: ל-commit SHA מלא (Dependabot יעדכן).").finalize(rel))
        if not re.search(r"^permissions:", text, re.M):
            out.append(Finding("workflow-no-permissions", "ו", "E4b", "low", CONF_CERTAIN,
                               "workflow בלי permissions בראשו", rel, 0, "",
                               "permissions: contents: read בראש הקובץ.").finalize(rel))
        run_indent = None   # בתוך בלוק run: רב-שורתי - העומק של המפתח run
        for i, ln in enumerate(ls, 1):
            indent = len(ln) - len(ln.lstrip())
            m_run = re.match(r"^(\s*)-?\s*run:\s*(.*)$", ln)
            if m_run:
                run_indent = indent if m_run.group(2).strip() in ("|", ">", "|-", ">-", "") else None
                in_run = True
            elif run_indent is not None and (not ln.strip() or indent > run_indent):
                in_run = True
            else:
                run_indent, in_run = None, False
            if "pull_request_target" in ln:
                out.append(_f("pull-request-target", "ו", "E4b", "high", CONF_SUSPECT,
                              "pull_request_target - קוד מ-PR זר רץ עם סודות", rel, i, ln,
                              "להחליף ב-pull_request, או לא לעשות checkout לקוד ה-PR."))
            # ${{ }} בתוך env: הוא הדרך הבטוחה - רק בתוך run: זו הזרקה (virtual-office, 23-09)
            if in_run and WF_INJECTION.search(ln):
                out.append(_f("workflow-injection", "ו", "E4b", "high", CONF_SUSPECT,
                              "טקסט שזר שולט בו מוזרק לפקודת run", rel, i, ln,
                              "להעביר דרך env: ולצטט כמשתנה, לא ${{ }} בתוך run."))
    manifests = [r for r in p.files if os.path.basename(r) in ("package.json", "pyproject.toml")
                 or re.match(r"requirements[\w.-]*\.txt$", os.path.basename(r))]
    top_has = lambda path: os.path.isfile(os.path.join(p.git_top or p.root, path))  # noqa: E731
    if manifests and p.git["is_repo"]:
        if not (top_has(".github/dependabot.yml") or top_has(".github/dependabot.yaml")):
            out.append(Finding("dependabot-missing", "ו", "E4c", "low", CONF_CERTAIN,
                               "אין .github/dependabot.yml", ".github/dependabot.yml", 0, "",
                               "להעתיק את baseline/dependabot.yml.").finalize("dependabot"))
        top_wfs = []
        wdir = os.path.join(p.git_top or p.root, ".github", "workflows")
        if os.path.isdir(wdir):
            for fn in os.listdir(wdir):
                try:
                    with open(os.path.join(wdir, fn), encoding="utf-8", errors="replace") as f:
                        top_wfs.append(f.read())
                except OSError:
                    pass
        if not any(re.search(r"gitleaks|osv-scanner|semgrep|codeql", w) for w in top_wfs):
            out.append(Finding("security-ci-missing", "ו", "E4e", "low", CONF_CERTAIN,
                               "אין סריקת אבטחה ב-CI (gitleaks / osv-scanner / semgrep)",
                               ".github/workflows/", 0, "",
                               "להעתיק את baseline/security-baseline.yml.").finalize("security-ci"))
    for rel in p.files:
        if not re.match(r"Dockerfile(?:\.[\w.-]+)?$", os.path.basename(rel)):
            continue
        t = p.text(rel)
        users = DOCKER_USER.findall(t)
        if not users or users[-1].lower() in ("root", "0", "0:0"):
            out.append(Finding("docker-root", "ו", "E4d", "low", CONF_CERTAIN,
                               "הקונטיינר רץ כ-root (אין USER לא-root)", rel, 0, "",
                               "משתמש ייעודי ו-USER לפני CMD.").finalize(rel))
        d = os.path.dirname(rel)
        di = os.path.join(p.root, d, ".dockerignore")
        di_text = ""
        if os.path.isfile(di):
            with open(di, encoding="utf-8", errors="replace") as f:
                di_text = f.read()
        if not re.search(r"^\s*\**/?\.env", di_text, re.M):
            out.append(Finding("dockerignore-env", "ו", "E4d", "medium", CONF_CERTAIN,
                               ".dockerignore לא מונע כניסת .env לתמונה", rel, 0, "",
                               "להוסיף .env ו-.env.* ל-.dockerignore שליד ה-Dockerfile.").finalize(rel + "|di"))
    return out


def d_report_mode(p: Project) -> list[Finding]:
    files = [r for r in p.files if (p.ext(r) in CODE_EXT | CONFIG_EXT or os.path.basename(r).startswith(".env"))
             and not TEST_PATH.search(r) and not r.endswith(("package-lock.json", ".lock"))]
    return [_f("report-only-mode", "ז", "—", "medium", CONF_SUSPECT,
               "שער שנראה כאילו הוא במצב דיווח בלבד (לא אוכף)", rel, i, ln,
               "מצב דיווח מותר רק עם תאריך יעד ומי שאחראי להדליק. /health מדווח enforced/DISABLED.")
            for rel, i, ln in p.iter_lines(files) if REPORT_MODE.search(ln)]


def d_gates_without_tests(p: Project) -> list[Finding]:
    gates = [(rel, i, ln) for rel, i, ln in p.iter_lines(p.code_files()) if GATE_CODE.search(ln)]
    if not gates:
        return []
    tests = [r for r in p.files if TEST_PATH.search(r) and p.ext(r) in CODE_EXT]
    if any(GATE_TEST.search(p.text(t)) for t in tests):
        return []
    rel, i, ln = gates[0]
    return [_f("gates-without-tests", "ז", "—", "medium", CONF_SUSPECT,
               f"יש {len(gates)} מקומות שדוחים גישה, ואף בדיקה לא מוודאת שהם דוחים", rel, i, ln,
               "לכל שער: בדיקה ששולחת בקשה בלי הרשאה ומצפה ל-401/403 - ולראות אותה נופלת כשמסירים את השער.")]


DETECTORS: list[tuple[str, str, str, callable]] = [
    # (מזהה, משפחה, מה הוא בודק - לשורת "נבדק", פונקציה)
    ("env-default-secret", "ב", "סודות שנופלים לערך כתוב בקוד כשהמשתנה חסר", d_env_default),
    ("fail-open-gate", "א", "שערים שנפתחים כשהסוד חסר", d_fail_open),
    ("secret-in-url", "ב", "סודות בתוך כתובות", d_secret_in_url),
    ("client-exposed-secret", "ב", "סודות בקידומת שנשלחת לדפדפן", d_client_secret),
    ("nonconstant-compare", "ב", "השוואת סוד שאינה קבועת-זמן", d_nonconst_compare),
    ("env-file-tracked", "ב", "קובצי .env בגיט ו-.gitignore", d_env_tracked),
    ("state-change-get", "א", "פעולות שמשנות מצב ב-GET", d_state_change_get),
    ("webhook-no-signature", "א", "webhooks בלי אימות חתימה", d_webhook_signature),
    ("bot-no-allowlist", "א", "בוטים בלי רשימת-מורשים", d_bot_allowlist),
    ("cors-wildcard", "א", "CORS פתוח לכל מקור", d_cors),
    ("migrations", "א", "מיגרציות: RLS, SECURITY DEFINER, views, הרשאות ברירת מחדל", d_migrations),
    ("pii-in-logs", "ג", "מידע אישי ביומנים", d_pii_logs),
    ("pii-data-file", "ג", "קובצי נתונים עם פרטי קשר של אנשים", d_pii_files),
    ("error-leak", "ג", "שגיאות פנימיות שחוזרות למשתמש", d_error_leak),
    ("no-rate-limit", "ד", "הגבלת קצב כלשהי בפרויקט שיש בו נתיבים או בוט", d_rate_limit),
    ("raw-html", "ה", "HTML גולמי", d_raw_html),
    ("html-from-request", "ה", "פרמטר מהבקשה בתוך HTML", d_html_from_request),
    ("markdown-unsanitized", "ה", "Markdown ל-HTML בלי sanitizer", d_markdown),
    ("sql-string-build", "ה", "SQL שנבנה ממחרוזת", d_sql),
    ("prompt-system-interpolation", "ה", "תוכן משתנה בתפקיד ה-system", d_prompt_system),
    ("supply-chain", "ו", "lockfile, actions נעולים, permissions, Dependabot, CI אבטחה, Docker", d_supply_chain),
    ("report-only-mode", "ז", "שערים במצב דיווח בלבד", d_report_mode),
    ("gates-without-tests", "ז", "שערים שאין בדיקה שמוכיחה שהם דוחים", d_gates_without_tests),
]

# --------------------------------------------------------------------------
# כלים חיצוניים - שלושת הסורקים שכבר רצים ב-CI (security-baseline.yml).
# לא מותקן / נכשל ← "לא נבדק", לעולם לא "תקין".
# --------------------------------------------------------------------------

def _run(cmd: list[str], timeout: int, cwd: str | None = None) -> tuple[int, str, str]:
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=cwd)
    return p.returncode, p.stdout, p.stderr


def _version(tool: str) -> str:
    try:
        rc, out, err = _run([tool, "--version"], 30)
        return (out or err).strip().splitlines()[0][:60] if rc == 0 else ""
    except (OSError, subprocess.TimeoutExpired, IndexError):
        return ""


def run_gitleaks(p: Project, history: bool) -> tuple[list[Finding], dict]:
    tool = shutil.which("gitleaks")
    if not tool:
        return [], {"ran": False, "reason": "gitleaks לא מותקן"}
    cfg = None
    for c in (os.path.join(p.git_top or p.root, ".gitleaks.toml"), os.path.expanduser("~/.githooks/gitleaks.toml")):
        if os.path.isfile(c):
            cfg = c
            break
    with tempfile.TemporaryDirectory() as td:
        rep = os.path.join(td, "gl.json")
        if history and p.git["is_repo"]:
            cmd = [tool, "git", p.git_top, "--report-format", "json", "--report-path", rep,
                   "--redact=100", "--no-banner", "--exit-code", "0"]
            mode = "היסטוריה מלאה"
        else:
            cmd = [tool, "dir", p.root, "--report-format", "json", "--report-path", rep,
                   "--redact=100", "--no-banner", "--exit-code", "0"]
            mode = "הקבצים של היום"
        ign = os.path.join(p.git_top or p.root, ".gitleaksignore")
        if os.path.isfile(ign):
            cmd += ["--gitleaks-ignore-path", ign]
        if cfg:
            cmd += ["--config", cfg]
        try:
            rc, _, err = _run(cmd, 900)
        except subprocess.TimeoutExpired:
            return [], {"ran": False, "reason": "gitleaks חרג מזמן הריצה"}
        if rc != 0 or not os.path.isfile(rep):
            return [], {"ran": False, "reason": f"gitleaks נכשל (קוד {rc})"}
        try:
            with open(rep, encoding="utf-8") as f:
                rows = json.load(f) or []
        except (OSError, json.JSONDecodeError):
            return [], {"ran": False, "reason": "gitleaks: דוח לא קריא"}
    wanted = set(p.files)
    out = []
    for r in rows:
        path = r.get("File", "")
        rel = os.path.relpath(path, p.root) if os.path.isabs(path) else path
        if history:
            rel = os.path.relpath(os.path.join(p.git_top, path), p.root) if p.git_top else path
        elif rel not in wanted:
            continue   # קובץ שגיט מתעלם ממנו (למשל .env מקומי) אינו ממצא
        commit = (r.get("Commit") or "")[:10]
        ev = f"כלל {r.get('RuleID', '?')}" + (f", commit {commit}" if commit else "") + " (הערך מוסתר)"
        out.append(Finding("gitleaks", "ב", "B3", "high", CONF_CERTAIN,
                           "סוד בקוד (gitleaks)" + (" - בהיסטוריה" if history else ""),
                           rel, int(r.get("StartLine") or 0), ev,
                           "להוציא מהקוד, להחליף את הסוד אצל הספק; אם הוחלט לקבל - לרשום ב-.security-accepted.json."
                           ).finalize(f"{r.get('RuleID')}|{rel}|{r.get('Fingerprint', '')}|{commit}"))
    return out, {"ran": True, "version": _version(tool), "mode": mode, "config": "מותאם" if cfg else "ברירת מחדל"}


def _osv_sev(v: dict) -> str:
    s = ((v.get("database_specific") or {}).get("severity") or "").upper()
    if s in ("CRITICAL", "HIGH"):
        return s.lower()
    if s in ("MODERATE", "MEDIUM"):
        return "medium"
    if s == "LOW":
        return "low"
    return "medium"


def run_osv(p: Project) -> tuple[list[Finding], dict]:
    tool = shutil.which("osv-scanner")
    if not tool:
        return [], {"ran": False, "reason": "osv-scanner לא מותקן"}
    with tempfile.TemporaryDirectory() as td:
        rep = os.path.join(td, "osv.json")
        try:
            rc, _, err = _run([tool, "scan", "source", "--recursive", "--format", "json",
                               "--output-file", rep, p.root], 900)
        except subprocess.TimeoutExpired:
            return [], {"ran": False, "reason": "osv-scanner חרג מזמן הריצה"}
        # 0 = נקי, 1 = נמצאו פרצות, 128 = אין מה לסרוק. כל השאר - תקלת כלי.
        if rc == 128:
            return [], {"ran": True, "version": _version(tool), "note": "לא נמצאו קובצי תלויות"}
        if rc not in (0, 1) or not os.path.isfile(rep):
            return [], {"ran": False, "reason": f"osv-scanner נכשל (קוד {rc})"}
        try:
            with open(rep, encoding="utf-8") as f:
                d = json.load(f)
        except (OSError, json.JSONDecodeError):
            return [], {"ran": False, "reason": "osv-scanner: דוח לא קריא"}
    out = []
    for res in d.get("results", []):
        src = res.get("source", {}).get("path", "")
        rel = os.path.relpath(src, p.root) if os.path.isabs(src) else src
        for pk in res.get("packages", []):
            vulns = pk.get("vulnerabilities", [])
            if not vulns:
                continue
            sev = min((_osv_sev(v) for v in vulns), key=lambda s: SEV_RANK[s])
            name, ver = pk["package"].get("name"), pk["package"].get("version")
            ids = sorted({v.get("id") for v in vulns})
            out.append(Finding("osv", "ו", "E4", sev, CONF_CERTAIN,
                               f"{name}@{ver}: {len(ids)} פרצות ידועות", rel, 0,
                               ", ".join(ids[:4]) + ("…" if len(ids) > 4 else ""),
                               "לעדכן לגרסה מתוקנת (Dependabot פותח PR לרוב).").finalize(f"{name}|{ver}|{rel}"))
    return out, {"ran": True, "version": _version(tool)}


def _semgrep_family(rule: str) -> str:
    r = rule.lower()
    if "secret" in r or "crypto" in r or "hash" in r or "jwt" in r:
        return "ב"
    if any(k in r for k in ("cors", "auth", "csrf", "permission")):
        return "א"
    if any(k in r for k in ("docker", "github-actions", "yaml")):
        return "ו"
    return "ה"


def run_semgrep(p: Project) -> tuple[list[Finding], dict]:
    tool = shutil.which("semgrep")
    if not tool:
        return [], {"ran": False, "reason": "semgrep לא מותקן"}
    cmd = [tool, "scan", "--config", "p/security-audit", "--config", "p/owasp-top-ten", "--config", "p/secrets",
           "--metrics=off", "--severity", "ERROR", "--json", "--quiet",
           "--exclude", "node_modules", "--exclude", ".next", "--exclude", "dist",
           "--exclude", "*.min.js", "--exclude", "*.md", p.root]
    try:
        rc, out_s, err = _run(cmd, 1200)
    except subprocess.TimeoutExpired:
        return [], {"ran": False, "reason": "semgrep חרג מזמן הריצה"}
    try:
        d = json.loads(out_s or "{}")
    except json.JSONDecodeError:
        return [], {"ran": False, "reason": f"semgrep נכשל (קוד {rc}; ייתכן שאין רשת לכללי-הרישום)"}
    if rc not in (0, 1) and not d.get("results"):
        return [], {"ran": False, "reason": f"semgrep נכשל (קוד {rc})"}
    out = []
    for r in d.get("results", []):
        path = r.get("path", "")
        rel = os.path.relpath(path, p.root) if os.path.isabs(path) else path
        rule = r.get("check_id", "?").split(".")[-1]
        out.append(Finding("semgrep", _semgrep_family(rule), "—", "medium", CONF_SUSPECT,
                           f"semgrep: {rule}", rel, int(r.get("start", {}).get("line") or 0),
                           snippet((r.get("extra") or {}).get("lines") or ""),
                           "לקרוא את הקוד ולהכריע - לפי ביקורת 09/2026 רוב ממצאי semgrep אינם פרצה.")
                   .finalize(f"{rule}|{rel}|{r.get('start', {}).get('line')}"))
    return out, {"ran": True, "version": _version(tool)}


# --------------------------------------------------------------------------
# משימות לבדיקת סוכן
# --------------------------------------------------------------------------

def _cands(rows, limit=40) -> list[dict]:
    seen, out = set(), []
    for rel, i, ln in rows:
        k = (rel, i)
        if k in seen:
            continue
        seen.add(k)
        out.append({"file": rel, "line": i, "snippet": snippet(ln)})
        if len(out) >= limit:
            break
    return out


def build_tasks(p: Project) -> list[Task]:
    tasks: list[Task] = []
    code = p.code_files()
    routes = _route_rows(p)

    id_routes = [(r["file"], r["line"], r["raw"]) for r in routes if ID_PARAM.search(r["path"] + " " + r["raw"])]
    id_lines = [(rel, i, ln) for rel, i, ln in p.iter_lines(code) if re.search(r"req\.params|request\.view_args|params\.\w*[iI]d\b", ln)]
    if id_routes or id_lines:
        tasks.append(Task("א-idor", "א", ["B4"],
                          "לכל פעולה שמקבלת מזהה מבחוץ: איפה נבדק שהמזהה הזה שייך למשתמש שקורא?",
                          "'מזוהה' אינו 'מורשה'. בסטודיו זה אפשר ביטול שיעור של תלמידה אחרת.",
                          _cands(id_routes + id_lines)))
    admin = [(r["file"], r["line"], r["raw"]) for r in routes if re.search(r"admin|dashboard|internal|manage", r["path"] + r["file"], re.I)]
    if admin:
        tasks.append(Task("א-admin", "א", ["A4", "A5"],
                          "כל נתיב ניהול: נבדקת הרשאה בצד השרת (לא רק בדפדפן)? מה רואה מי שנכנס בלי סיסמה?",
                          "'אף אחד לא יודע את הכתובת' אינה תשובה - 13 דפי ניהול היו פתוחים חצי שנה.",
                          _cands(admin)))
    hooks = [(r["file"], r["line"], r["raw"]) for r in routes if re.search(r"hook", r["path"] + r["file"], re.I)]
    bots = [(rel, 1, (p.lines(rel) or [""])[0]) for rel in code if BOT_HANDLER.search(p.text(rel))]
    if hooks or bots:
        tasks.append(Task("א-inbound", "א", ["E2", "F2"],
                          "כל webhook ובוט: האימות נאכף בפועל (לא במצב דיווח), ונכשל-סגור כשהסוד חסר? "
                          "מי יכול לשלוח לו, ומה קורה אז?",
                          "בנועם כל אדם יכול היה להזריק 'הודעת ליד' מכל מספר, והבוט ענה בשם המותג.",
                          _cands(hooks + bots)))
    secret_reads = [(rel, i, ln) for rel, i, ln in p.iter_lines(code)
                    if re.search(r"(?:os\.environ|getenv|process\.env)[^\n]*" + _SECRET_NAME, ln, re.I)]
    if secret_reads:
        tasks.append(Task("ב-secrets", "ב", ["B2", "F3"],
                          "לכל קריאת סוד: מה קורה כשהמשתנה לא מוגדר בייצור? ואילו מפתחות השירות מחזיק - "
                          "מה אפשר לעשות איתם אם הוא ייפרץ?",
                          "ב-noam-whatsapp נמדד שהמשתנים אינם מוגדרים בייצור - ברירות-המחדל בקוד היו הסודות החיים.",
                          _cands(secret_reads)))
    logs = [(rel, i, ln) for rel, i, ln in p.iter_lines(code) if LOG_CALL.search(ln)
            and re.search(r"(body|payload|message|phone|mail|user|lead|name|text|data)", ln, re.I)]
    if logs:
        tasks.append(Task("ג-logs", "ג", ["E1", "D1"],
                          "מה בדיוק נכנס ליומן? טלפון, מייל, שם, תוכן שיחה, טוקן? יש helper לרדקציה?",
                          "היומן של נועם כתב טלפון מלא ותוכן שיחה בכל תור - בניגוד לשאר אותו קובץ, שבו המיסוך כן קיים.",
                          _cands(logs)))
    paid = [(rel, i, ln) for rel, i, ln in p.iter_lines(code) if PAID_API.search(ln)]
    if paid:
        tasks.append(Task("ד-cost", "ד", ["C1", "F4"],
                          "מה שעולה כסף או ששולח משהו: מי יכול להפעיל אותו בלי אימות, ובכמה? "
                          "יש תקרה על קצב וגם על גודל בקשה?",
                          "בוט הטלגרם הריץ תמלול, שני מודלים ומייל לכל מי שמצא אותו, בלי הגבלה.",
                          _cands(paid)))
    llm_files = [rel for rel in code if LLM_CALL.search(p.text(rel))]
    llm = [(rel, i, ln) for rel, i, ln in p.iter_lines(code) if LLM_CALL.search(ln) or PROMPT_SYSTEM.search(ln)]
    llm += [(rel, i, ln) for rel, i, ln in p.iter_lines(llm_files) if PROMPT_INJECT_VAR.search(ln)]
    if llm:
        tasks.append(Task("ה-prompts", "ה", ["F1", "F2"],
                          "כל מחרוזת שנכנסת לפרומפט: מי כתב אותה, ובאיזה תפקיד היא נוחתת (system או messages)? "
                          "כלים שהמודל מפעיל - ברשימת-היתר ומאומתים בשרת? פעולה בלתי-הפיכה דורשת אדם?",
                          "בנועם הקשר משיחות קודמות של הליד הוזרק למקום של ההוראות.",
                          _cands(llm)))
    html_files = code + [r for r in p.files if p.ext(r) in (".html", ".jinja", ".j2", ".hbs") and not TEST_PATH.search(r)]
    html = [(rel, i, ln) for rel, i, ln in p.iter_lines(html_files) if RAW_HTML.search(ln) or HTML_FROM_REQUEST.search(ln)
            or re.search(r"<(?:div|p|a|td|li|span|h\d)[^>]*>\s*['\"]?\s*\+|\$\{[^}]+\}\s*</", ln)]
    if html:
        tasks.append(Task("ה-html", "ה", ["C4"],
                          "כל HTML (דף או מייל) שמורכב מתוכן שמשתמש או מודל שולטים בו - עובר escape?",
                          "בסטודיו שם-תצוגה שהלקוחה בוחרת נכנס בלי סינון למייל למנטור.",
                          _cands(html)))
    gates = [(rel, i, ln) for rel, i, ln in p.iter_lines(code) if GATE_CODE.search(ln) or SIG_TOKENS.search(ln)]
    if gates:
        tasks.append(Task("ז-gates", "ז", ["—"],
                          "לכל שער: יש בדיקה שנכשלת כשמסירים אותו? הוא אוכף, או במצב דיווח? "
                          "/health מדווח את מצב האכיפה ושיעור הדחיות?",
                          "תיקון שסגר 8 מתוך 31 פונקציות 'עבר' כי השומר בדק רשימה קשיחה.",
                          _cands(gates)))
    return tasks


# --------------------------------------------------------------------------
# סיכונים שהוחלט לקבל
# --------------------------------------------------------------------------

def load_accepted(p: Project, path: str | None) -> tuple[list[dict], list[str]]:
    cand = path or os.path.join(p.git_top or p.root, ".security-accepted.json")
    if not os.path.isfile(cand):
        return [], []
    try:
        with open(cand, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        return [], [f"קובץ הסיכונים המקובלים לא קריא ({type(e).__name__}) - אף סיכון לא הוחרג"]
    rules, warn = [], []
    for n, a in enumerate(data.get("accepted", []), 1):
        missing = [k for k in ("reason", "decided") if not a.get(k)]
        if missing:
            warn.append(f"סיכון מקובל #{n} חסר {', '.join(missing)} - לא הוחרג")
            continue
        if not (a.get("key") or a.get("detector")):
            warn.append(f"סיכון מקובל #{n} בלי key או detector - לא הוחרג")
            continue
        rules.append(a)
    return rules, warn


def _accepted_match(f: Finding, rules: list[dict]) -> dict | None:
    for a in rules:
        if a.get("key") and a["key"] == f.key:
            return a
        if a.get("detector") and a["detector"] == f.detector and fnmatch.fnmatch(f.file, a.get("file", "*")):
            return a
    return None


# --------------------------------------------------------------------------
# הרכבת התוצאה
# --------------------------------------------------------------------------

def scan(root: str, out_dir: str, external: bool, history: bool, accepted_path: str | None,
         want_semgrep: bool) -> dict:
    p = Project(root)
    p.load()
    findings: list[Finding] = []
    checked: dict[str, list[str]] = {k: [] for k in FAMILIES}
    not_checked: dict[str, list[str]] = {k: [] for k in FAMILIES}

    for det_id, fam, what, fn in DETECTORS:
        try:
            res = fn(p)
        except Exception as e:  # גלאי שקרס אינו "לא מצא" - הוא "לא נבדק"
            not_checked[fam].append(f"{what} - הגלאי קרס ({type(e).__name__})")
            continue
        findings.extend(res)
        checked[fam].append(what)

    if not p.git["is_repo"]:
        not_checked["ב"].append("קובצי .env בגיט - התיקייה אינה ריפו גיט")

    tools = {}
    if external:
        for name, runner, fams in (("gitleaks", lambda: run_gitleaks(p, history), ["ב"]),
                                   ("osv-scanner", lambda: run_osv(p), ["ו"]),
                                   ("semgrep", lambda: run_semgrep(p) if want_semgrep else
                                    ([], {"ran": False, "reason": "דולג (--no-semgrep)"}), ["א", "ה"])):
            try:
                res, status = runner()
            except Exception as e:
                res, status = [], {"ran": False, "reason": f"{name} קרס ({type(e).__name__})"}
            tools[name] = status
            findings.extend(res)
            for fam in fams:
                (checked if status.get("ran") else not_checked)[fam].append(
                    f"{name}" + (f" ({status.get('mode')})" if status.get("mode") else "")
                    if status.get("ran") else f"{name} - {status.get('reason')}")
    else:
        for name, fams in (("gitleaks", ["ב"]), ("osv-scanner", ["ו"]), ("semgrep", ["א", "ה"])):
            tools[name] = {"ran": False, "reason": "דולג (--no-external)"}
            for fam in fams:
                not_checked[fam].append(f"{name} - דולג (--no-external)")

    # כפילויות (אותו מפתח משני גלאים) - משאירים את הראשון
    uniq: dict[str, Finding] = {}
    for f in findings:
        uniq.setdefault(f.key, f)
    findings = list(uniq.values())

    rules, warnings = load_accepted(p, accepted_path)
    open_f, accepted = [], []
    for f in findings:
        a = _accepted_match(f, rules)
        if a:
            accepted.append({**asdict(f), "accepted_reason": a["reason"], "accepted_on": a["decided"],
                             "accepted_by": a.get("by", ""), "revisit": a.get("revisit", "")})
        else:
            open_f.append(f)
    gl_ignore = os.path.join(p.git_top or p.root, ".gitleaksignore")
    gl_count = 0
    if os.path.isfile(gl_ignore):
        with open(gl_ignore, encoding="utf-8", errors="replace") as fh:
            gl_count = sum(1 for x in fh if x.strip() and not x.startswith("#"))

    tasks = build_tasks(p)
    result = {
        "schema_version": SCHEMA_VERSION,
        "engine_version": ENGINE_VERSION,
        "scanned_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "project": {"name": p.name, "path": p.root, "git": p.git},
        "scope": {"files": len(p.files), "code_files": len(p.code_files()),
                  "ignore_patterns": len(p.ignore_globs)},
        "tools": tools,
        "checked": checked,
        "not_checked": not_checked,
        "findings": [asdict(f) for f in sorted(open_f, key=lambda f: (SEV_RANK[f.severity], f.family, f.file, f.line))],
        "accepted_risks": accepted,
        "gitleaksignore_entries": gl_count,
        "judgment_tasks": [asdict(t) for t in tasks],
        "reviews": [],
        "warnings": p.warnings + warnings,
    }
    finalize(result)
    write_outputs(result, out_dir)
    return result


def finalize(result: dict) -> None:
    """מחשב את מצב המשפחות ואת הסיכום. רץ גם אחרי merge."""
    fams = {}
    for k, meta in FAMILIES.items():
        fs = [f for f in result["findings"] if f["family"] == k]
        pending = [t["id"] for t in result["judgment_tasks"] if t["family"] == k and t["status"] == "ממתין"]
        nc = result["not_checked"].get(k, []) + [
            f"משימה {t['id']} - {t['status']}" for t in result["judgment_tasks"]
            if t["family"] == k and t["status"] == "לא נבדק"]
        if fs:
            status = "נמצאו ממצאים"
        elif pending:
            status = "ממתין לבדיקת סוכן"
        elif nc:
            status = "נבדק חלקית"
        elif result["checked"].get(k):
            status = "נבדק, לא נמצא"
        else:
            status = "לא נבדק"
        fams[k] = {"name": meta["name"], "status": status, "findings": len(fs),
                   "by_severity": {s: sum(1 for f in fs if f["severity"] == s) for s in SEVERITIES},
                   "checked": result["checked"].get(k, []), "not_checked": nc, "pending_tasks": pending}
    result["families"] = fams
    by_sev = {s: sum(1 for f in result["findings"] if f["severity"] == s) for s in SEVERITIES}
    pending = [t["id"] for t in result["judgment_tasks"] if t["status"] == "ממתין"]
    certain_high = sum(1 for f in result["findings"] if f["severity"] in ("critical", "high")
                       and f["confidence"] != CONF_SUSPECT)
    result["summary"] = {
        "open_findings": len(result["findings"]),
        "by_severity": by_sev,
        "certain_high": certain_high,
        "accepted": len(result["accepted_risks"]),
        "pending_tasks": len(pending),
        "exit_code": 1 if by_sev["critical"] or by_sev["high"] else 0,
    }


def exit_code(result: dict, fail_on: str) -> int:
    """high = כל ממצא קריטי/גבוה, גם חשוד (ברירת מחדל - לאדם ולסוכן).
    certain-high = רק מה שהמכונה הכריעה או שסוכן אישר (ל-CI: חשוד שעוצר את כולם
    הוא שומר שנושך יותר מדי, ומכבים אותו - משפחה ז, הצורה החמישית).
    none = לעולם לא נכשל על ממצאים (רק על תקלה)."""
    if fail_on == "none":
        return 0
    if fail_on == "certain-high":
        return 1 if result["summary"]["certain_high"] else 0
    return result["summary"]["exit_code"]


# --------------------------------------------------------------------------
# פלט
# --------------------------------------------------------------------------

def _md_cell(s) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def render_md(r: dict) -> str:
    g = r["project"]["git"]
    s = r["summary"]
    date = r["scanned_at"][:10]
    lines = [f"# {r['project']['name']} - ביקורת אבטחה ({date})", ""]
    where = f"commit: `{g.get('commit')}`, ענף: `{g.get('branch')}`" if g.get("is_repo") else "לא ריפו גיט"
    lines.append(f"מה נסרק: {r['scope']['files']} קבצים ({r['scope']['code_files']} קובצי קוד), {where}. "
                 f"מנוע {r['engine_version']}.")
    lines.append("")
    sev_line = " · ".join(f"{SEV_HE[k]} {v}" for k, v in s["by_severity"].items() if v) or "אין"
    lines.append(f"**בשורה אחת:** {s['open_findings']} ממצאים פתוחים ({sev_line}), "
                 f"{s['pending_tasks']} משימות ממתינות לבדיקת סוכן, {s['accepted']} סיכונים שהוחלט לקבל.")
    lines.append("")
    lines.append("> כל ממצא כאן **הוסק מקוד** - לא אומת חי. 'ודאי' = המכונה הכריעה; 'חשוד' = דפוס שנראה כמו "
                 "הכשל, וסוכן צריך לאשר. ערכי סודות לעולם אינם מוצגים.")
    lines += ["", "## מצב לפי משפחה", "", "| משפחה | מצב | ממצאים | ממתין לסוכן | לא נבדק |", "|---|---|---|---|---|"]
    for k, fm in r["families"].items():
        lines.append(f"| {k} - {fm['name']} | {fm['status']} | {fm['findings']} | "
                     f"{len(fm['pending_tasks'])} | {_md_cell('; '.join(fm['not_checked'])) or '-'} |")
    lines += ["", "## ממצאים", ""]
    if r["findings"]:
        lines += ["| ID | חומרה | ודאות | משפחה | סעיף | מה נמצא | ראיה | תיקון מוצע |", "|---|---|---|---|---|---|---|---|"]
        for n, f in enumerate(r["findings"], 1):
            loc = f"`{f['file']}:{f['line']}`" if f["line"] else f"`{f['file']}`"
            ev = f" - {_md_cell(f['evidence'])}" if f["evidence"] else ""
            lines.append(f"| S{n:02d} | {SEV_HE[f['severity']]} | {f['confidence']} | {f['family']} | {f['item']} | "
                         f"{_md_cell(f['title'])} | {loc}{ev} | {_md_cell(f['fix'])} |")
    else:
        lines.append("אין ממצאים פתוחים.")
    probes = [f for f in r["findings"] if f.get("probe")]
    if probes:
        lines += ["", "## רשימת בדיקות חיות", "", "| מה | בדיקה | איפה בקוד |", "|---|---|---|"]
        for f in probes:
            lines.append(f"| {_md_cell(f['title'])} | {_md_cell(f['probe'])} | `{f['file']}:{f['line']}` |")
    tasks = [t for t in r["judgment_tasks"] if t["status"] == "ממתין"]
    lines += ["", "## ממתין לבדיקת סוכן", ""]
    if tasks:
        lines.append("ההוראות המלאות, כולל המקומות בקוד: `review-brief.md` שליד הדוח.")
        lines.append("")
        for t in tasks:
            lines.append(f"- **{t['id']}** ({len(t['candidates'])} מקומות): {t['question']}")
    else:
        lines.append("אין.")
    if r["reviews"]:
        lines += ["", "## מה סוכן בדק", ""]
        for rv in r["reviews"]:
            lines.append(f"- **{rv['task_id']}** - {rv['verdict']} ({rv.get('reviewer', '')}, {rv.get('reviewed_at', '')})"
                         + (f": {rv['notes']}" if rv.get("notes") else ""))
    lines += ["", "## מה נבדק ונמצא תקין", ""]
    for k, fm in r["families"].items():
        clean = fm["checked"] if not fm["findings"] else []
        if clean:
            lines.append(f"- **{k}:** " + "; ".join(clean))
    lines += ["", "## מה לא נבדק ולמה", ""]
    any_nc = False
    for k, fm in r["families"].items():
        for x in fm["not_checked"]:
            lines.append(f"- **{k}:** {x}")
            any_nc = True
    lines.append("- **תמיד:** בדיקה חיה (קריאות אמיתיות לשירות), הגדרות אצל ספק האירוח, והיסטוריית הגיט "
                 "(אלא אם הורץ עם --history).")
    if not any_nc:
        pass
    if r["accepted_risks"] or r.get("gitleaksignore_entries"):
        lines += ["", "## סיכונים שהוחלט לקבל", ""]
        for a in r["accepted_risks"]:
            lines.append(f"- {a['title']} (`{a['file']}`) - {a['accepted_reason']} "
                         f"(הוחלט {a['accepted_on']}{', ' + a['accepted_by'] if a.get('accepted_by') else ''})")
        if r.get("gitleaksignore_entries"):
            lines.append(f"- `.gitleaksignore`: {r['gitleaksignore_entries']} שורות שסורק הסודות מדלג עליהן.")
    if r["warnings"]:
        lines += ["", "## אזהרות", ""] + [f"- {w}" for w in r["warnings"]]
    lines += ["", "## כלים", ""]
    for name, st in r["tools"].items():
        lines.append(f"- {name}: " + (f"רץ ({st.get('version', '')}{', ' + st['mode'] if st.get('mode') else ''})"
                                      if st.get("ran") else f"לא רץ - {st.get('reason')}"))
    return "\n".join(lines) + "\n"


def render_brief(r: dict, audit_path: str) -> str:
    tasks = [t for t in r["judgment_tasks"] if t["status"] == "ממתין"]
    L = [f"# בדיקת סוכן - {r['project']['name']} ({r['scanned_at'][:10]})", "",
         "הבדיקות המכניות רצו. מה שנשאר דורש **קריאת קוד ושיקול דעת** - וזה החלק שבו נמצאו כל 13 "
         "הממצאים הקריטיים והגבוהים של ביקורת 09/2026.", "",
         "## איך עונים", "",
         "1. לכל משימה: לקרוא את המקומות שברשימה **ואת הקוד שסביבם** (הרשימה היא נקודת פתיחה, לא גבול).",
         "2. לענות בקובץ JSON אחד, בפורמט שבסוף.",
         "3. להריץ:", "", "```bash",
         f"python3 \"{os.path.abspath(__file__)}\" merge \"{audit_path}\" review.json", "```", "",
         "**כללים:** לעולם לא להעתיק ערך של סוד לתשובה. 'לא נבדק' עדיף על ניחוש - ולצרף למה. "
         "חומרה: קריטי (נתונים/כסף חשופים בלי אימות) · גבוה (שער שנפתח בתנאי סביר) · בינוני · נמוך.", ""]
    for t in tasks:
        L += [f"## {t['id']} - משפחה {t['family']} ({FAMILIES[t['family']]['name']})", "",
              f"**השאלה:** {t['question']}", "", f"**למה:** {t['why']}", "",
              f"**סעיפי הצ'קליסט:** {', '.join(t['items'])}", "", "**איפה להתחיל:**", ""]
        L += [f"- `{c['file']}:{c['line']}` - `{c['snippet']}`" for c in t["candidates"]]
        L.append("")
    if not tasks:
        L.append("אין משימות ממתינות.")
    L += ["## פורמט התשובה", "", "```json", json.dumps({
        "reviewer": "<מי בדק>", "reviewed_at": "YYYY-MM-DD",
        "reviews": [{"task_id": tasks[0]["id"] if tasks else "<id>", "verdict": "ממצא",
                     "notes": "מה נבדק ואיך",
                     "findings": [{"title": "...", "severity": "high", "file": "src/x.py", "line": 12,
                                   "item": "B4", "fix": "...", "probe": "GET /x/123 כמשתמש אחר ← 403"}]},
                    {"task_id": "<id>", "verdict": "תקין", "notes": "איפה ההגנה"},
                    {"task_id": "<id>", "verdict": "לא נבדק", "notes": "למה"}]}, ensure_ascii=False, indent=2),
          "```", ""]
    return "\n".join(L)


def write_outputs(result: dict, out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    ap = os.path.join(out_dir, "audit.json")
    with open(ap, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    with open(os.path.join(out_dir, "audit.md"), "w", encoding="utf-8") as f:
        f.write(render_md(result))
    with open(os.path.join(out_dir, "review-brief.md"), "w", encoding="utf-8") as f:
        f.write(render_brief(result, ap))


# --------------------------------------------------------------------------
# merge - הכנסת התשובות של הסוכן
# --------------------------------------------------------------------------

VERDICTS = {"ממצא": "ממצא", "finding": "ממצא", "תקין": "תקין", "ok": "תקין",
            "לא נבדק": "לא נבדק", "not_checked": "לא נבדק"}


class ReviewError(ValueError):
    pass


def merge(audit_path: str, review_path: str) -> dict:
    with open(audit_path, encoding="utf-8") as f:
        result = json.load(f)
    with open(review_path, encoding="utf-8") as f:
        review = json.load(f)
    if result.get("schema_version") != SCHEMA_VERSION:
        raise ReviewError(f"audit.json בגרסת סכמה {result.get('schema_version')}, המנוע מכיר {SCHEMA_VERSION}")
    tasks = {t["id"]: t for t in result["judgment_tasks"]}
    reviews = review.get("reviews")
    if not isinstance(reviews, list) or not reviews:
        raise ReviewError("אין רשימת reviews בקובץ התשובה")
    new_findings = []
    for rv in reviews:
        tid = rv.get("task_id")
        if tid not in tasks:
            raise ReviewError(f"משימה לא מוכרת: {tid!r}")
        verdict = VERDICTS.get(str(rv.get("verdict", "")).strip().lower()) or VERDICTS.get(str(rv.get("verdict", "")).strip())
        if not verdict:
            raise ReviewError(f"{tid}: verdict חייב להיות ממצא / תקין / לא נבדק")
        if verdict == "ממצא" and not rv.get("findings"):
            raise ReviewError(f"{tid}: verdict 'ממצא' בלי findings")
        if verdict == "לא נבדק" and not rv.get("notes"):
            raise ReviewError(f"{tid}: 'לא נבדק' חייב לומר למה (notes)")
        for fd in rv.get("findings", []) if verdict == "ממצא" else []:
            sev = SEV_FROM_ANY.get(str(fd.get("severity", "")).strip().lower()) or SEV_FROM_ANY.get(str(fd.get("severity", "")).strip())
            if not sev:
                raise ReviewError(f"{tid}: חומרה לא מוכרת {fd.get('severity')!r}")
            if not fd.get("title") or not fd.get("file"):
                raise ReviewError(f"{tid}: לכל ממצא נדרשים title ו-file")
            f = Finding(f"review:{tid}", tasks[tid]["family"], fd.get("item") or ",".join(tasks[tid]["items"]),
                        sev, CONF_REVIEWED, redact(str(fd["title"])), str(fd["file"]), int(fd.get("line") or 0),
                        redact(str(fd.get("evidence", ""))), redact(str(fd.get("fix", ""))),
                        redact(str(fd.get("probe", ""))), source="review")
            new_findings.append(asdict(f.finalize(f"{fd['title']}|{fd.get('line')}")))
        tasks[tid]["status"] = {"ממצא": "נבדק - נמצא", "תקין": "נבדק - תקין", "לא נבדק": "לא נבדק"}[verdict]
        result["reviews"].append({"task_id": tid, "verdict": verdict, "notes": redact(str(rv.get("notes", ""))),
                                  "reviewer": review.get("reviewer", ""), "reviewed_at": review.get("reviewed_at", "")})
    existing = {f["key"] for f in result["findings"]}
    result["findings"] += [f for f in new_findings if f["key"] not in existing]
    result["findings"].sort(key=lambda f: (SEV_RANK[f["severity"]], f["family"], f["file"], f["line"]))
    finalize(result)
    write_outputs(result, os.path.dirname(os.path.abspath(audit_path)))
    return result


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def default_out(root: str) -> str:
    p = Project(root)
    rc, top = p._git("rev-parse", "--show-toplevel")
    name = os.path.basename(top.strip()) if rc == 0 and top.strip() else os.path.basename(os.path.abspath(root))
    sub = os.path.relpath(os.path.abspath(root), top.strip()) if rc == 0 and top.strip() else "."
    if sub != ".":
        name += "__" + sub.replace(os.sep, "_")
    return os.path.join(os.path.expanduser("~/Documents/security-audit"), name)


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] not in ("scan", "merge", "-h", "--help", "--version"):
        argv.insert(0, "scan")
    ap = argparse.ArgumentParser(prog="audit.py", description="מנוע ביקורת אבטחה - שבע משפחות הכשל")
    ap.add_argument("--version", action="version", version=f"audit.py {ENGINE_VERSION} (schema {SCHEMA_VERSION})")
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("scan", help="סריקת פרויקט")
    s.add_argument("path")
    s.add_argument("--out", help="תיקיית התוצרים (ברירת מחדל: ~/Documents/security-audit/<פרויקט>)")
    s.add_argument("--no-external", action="store_true", help="בלי gitleaks / osv-scanner / semgrep")
    s.add_argument("--no-semgrep", action="store_true", help="בלי semgrep (האיטי מבין השלושה)")
    s.add_argument("--history", action="store_true", help="gitleaks על כל היסטוריית הגיט")
    s.add_argument("--accepted", help="קובץ סיכונים מקובלים (ברירת מחדל: .security-accepted.json בשורש)")
    s.add_argument("--fail-on", choices=("high", "certain-high", "none"), default="high",
                   help="מתי קוד היציאה 1 (ברירת מחדל: כל ממצא קריטי/גבוה; ב-CI: certain-high)")
    s.add_argument("--quiet", action="store_true")
    m = sub.add_parser("merge", help="הכנסת תשובות הסוכן לתוצאה")
    m.add_argument("audit_json")
    m.add_argument("review_json")
    args = ap.parse_args(argv)

    if args.cmd == "merge":
        try:
            r = merge(args.audit_json, args.review_json)
        except (OSError, json.JSONDecodeError, ReviewError) as e:
            print(f"❌ merge נכשל: {e}", file=sys.stderr)
            return 2
        print(f"✅ התשובות נכנסו. ממצאים פתוחים: {r['summary']['open_findings']}, "
              f"משימות ממתינות: {r['summary']['pending_tasks']}")
        return r["summary"]["exit_code"]

    if not os.path.isdir(args.path):
        print(f"❌ אין תיקייה כזו: {args.path}", file=sys.stderr)
        return 2
    out = args.out or default_out(args.path)
    try:
        r = scan(args.path, out, not args.no_external, args.history, args.accepted, not args.no_semgrep)
    except Exception as e:
        print(f"❌ המנוע נכשל: {type(e).__name__}: {e}", file=sys.stderr)
        return 2
    if not args.quiet:
        s = r["summary"]
        print(f"🔍 {r['project']['name']}: {s['open_findings']} ממצאים פתוחים "
              f"(קריטי {s['by_severity']['critical']}, גבוה {s['by_severity']['high']}, "
              f"בינוני {s['by_severity']['medium']}, נמוך {s['by_severity']['low']}), "
              f"{s['pending_tasks']} משימות לבדיקת סוכן.")
        for k, fm in r["families"].items():
            print(f"   {k} {fm['name']}: {fm['status']}")
        nc = [t for t, st in r["tools"].items() if not st.get("ran")]
        if nc:
            print(f"⚠️ לא רצו: {', '.join(nc)} - מה שהם בודקים סומן 'לא נבדק'.")
        print(f"📄 {os.path.join(out, 'audit.md')}")
    return exit_code(r, args.fail_on)


if __name__ == "__main__":
    sys.exit(main())
